#!/bin/sh /etc/rc.common

START=20
STOP=10

USE_PROCD=1
PROG=/sbin/ponmgr

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	procd_send_signal "$PROG"
}
