#
# Automatically generated file; DO NOT EDIT.
# Main menu
#
# TCSUPPORT_CPU_EN7523 is not set
# TCSUPPORT_CPU_EN7551 is not set
# TCSUPPORT_CPU_AN7552 is not set
# TCSUPPORT_CPU_EN7581 is not set
TCSUPPORT_CPU_AN7583=y
TCSUPPORT_BOARD_SELECT=y
TCSUPPORT_CPU_ARMV8=y
TCSUPPORT_CPU_ARMV8_64=y
TCSUPPORT_LITTLE_ENDIAN=y
TCSUPPORT_GCC10_3_0_GLIBC2_32_KERNEL5_4=y
TCSUPPORT_5_4_KERNEL=y
# TCSUPPORT_DM_VERITY is not set
TCSUPPORT_POWER_SAVING=y
WAN_ETHER=y
WAN_GPON=y
WAN_EPON=y

#
# WAN Transfer Mode Support
#
TCSUPPORT_WAN_ETHER=y
# TCSUPPORT_QDMA_WAN_FOR_ETHER is not set
TCSUPPORT_WAN_GPON=y
TCSUPPORT_WAN_EPON=y
# end of WAN Transfer Mode Support

TCSUPPORT_UBOOT=y
# TCSUPPORT_UBOOT_2014 is not set
TCSUPPORT_UBOOT_2023=y
TCSUPPORT_UBOOT_64BIT=y
# TCSUPPORT_ARM_MULTIBOOT is not set
TCSUPPORT_ATF_2_10=y
TCSUPPORT_TPL_SUPPORT=y
TCSUPPORT_OPTEE=y
TCSUPPORT_ARM_SECURE_BOOT=y
TCSUPPORT_INIC_SPEEDUP=y

# TCSUPPORT_SECURE_BOOT_FLASH_KEY is not set
TCSUPPORT_BL2_OPTIMIZATION=y

#
# Driver Feature
#
TCSUPPORT_KERNEL_API=y
# TCSUPPORT_AUTOBENCH is not set
# TCSUPPORT_INIC is not set
# TCSUPPORT_DSL_PHYMODE is not set
# TCSUPPORT_DSL_PHYMODE_HOST is not set
TCSUPPORT_NPU=y
TCSUPPORT_NPU_TUNNEL_OFFLOAD=y
TCSUPPORT_NPU_WIFI_OFFLOAD=y
TCSUPPORT_NPU_WIFI_TX=y
# TCSUPPORT_TR68LED is not set
TCSUPPORT_I2C=y
TCSUPPORT_SOE=y
# TCSUPPORT_LEDKEY is not set
TCSUPPORT_WLAN=y
# TCSUPPORT_WLAN_MULTI_CHIP is not set
# TCSUPPORT_WLAN_APCLIENT is not set
TCSUPPORT_WLAN_8021X=y
# TCSUPPORT_WLAN_8021X_EXT is not set
# TCSUPPORT_DOT11N_SPEC_COMPLY is not set
# TCSUPPORT_WPA2_PRE_AUTH is not set
TCSUPPORT_WLAN_WPS=y
# WPS_BTN_NOT_SUPPORT_5G is not set
# TCSUPPORT_WPS_5G_BTN is not set
TCSUPPORT_WPS_BTN_DUALBAND=y
TCSUPPORT_WLAN_WDS=y
TCSUPPORT_WLAN_IGMPSNOOP=y
# TCSUPPORT_WLAN_TR181 is not set
# TCSUPPORT_WLAN_DOT11K_RRM is not set
# TCSUPPORT_WLAN_DOT11V_WNM is not set
# TCSUPPORT_WLAN_BNDSTRG is not set
# TCSUPPORT_WLAN_DOT11R_FT is not set
# TCSUPPORT_WLAN_VLAN is not set
# TCSUPPORT_HTBW_40M is not set
TCSUPPORT_WLAN_ATE=y
TCSUPPORT_WLAN_QATOOL=y
TCSUPPORT_WLAN_WPS_LEDSPEC=y
TCSUPPORT_WLAN_MULTI_WPS=y
TCSUPPORT_WLAN_GPIO=y
# TCSUPPORT_WLAN_LED_BY_SW is not set
TCSUPPORT_WLAN_PERSSID_SWITCH=y
# TCSUPPORT_WLAN_PERSSID_SWITCH_ENHANCE is not set
# TCSUPPORT_WLAN_PERSSID_RATELIMIT is not set
TCSUPPORT_WLAN_PMF=y
# TCSUPPORT_TEST_WLAN_SHORTCUT is not set
TCSUPPORT_WLAN_TXBF=y
# TCSUPPORT_SINGLE_SKU_V2 is not set
TCSUPPORT_EEPROM_ACEXT=y
# TCSUPPORT_MIPS_SYNCTYPE10 is not set
# TCSUPPORT_WLAN_MT7915_BUILD_IN is not set
TCSUPPORT_WLAN_MT7915_V74=y
TCSUPPORT_WLAN_MT7915_TXOFFLOAD=y
TCSUPPORT_WLAN_WPA3=y
TCSUPPORT_WLAN_AX=y
# TCSUPPORT_WLAN_INODE is not set
# TCSUPPORT_ECNT_MAP is not set
# TCSUPPORT_ECNT_MAP_ENHANCE is not set
# TCSUPPORT_EASYMESH_R13 is not set
# TCSUPPORT_MAP_FILTER is not set
# TCSUPPORT_MAP_WAPP is not set
# TCSUPPORT_MAP_1905DAEMON is not set
# TCSUPPORT_MAP_LIBMAPD is not set
# TCSUPPORT_MAP_MAPDAEMON is not set
# TCSUPPORT_FIRST_IF_NONE is not set
# TCSUPPORT_FIRST_IF_RT2561 is not set
# TCSUPPORT_FIRST_IF_RT3390 is not set
# TCSUPPORT_FIRST_IF_RT5392 is not set
# TCSUPPORT_FIRST_IF_RT5390 is not set
# TCSUPPORT_FIRST_IF_RT5390HL is not set
# TCSUPPORT_FIRST_IF_RT3090 is not set
# TCSUPPORT_FIRST_IF_MT7601E is not set
# TCSUPPORT_FIRST_IF_MT7592 is not set
# TCSUPPORT_FIRST_IF_MULTIDRIVER is not set
# TCSUPPORT_FIRST_IF_RT5592 is not set
# TCSUPPORT_FIRST_IF_RT3593 is not set
# TCSUPPORT_FIRST_IF_RT5592_RT3593 is not set
# TCSUPPORT_FIRST_IF_MT7610E is not set
# TCSUPPORT_FIRST_IF_MT7612E is not set
# TCSUPPORT_FIRST_IF_MT7613E is not set
# TCSUPPORT_FIRST_IF_MT7615_11N is not set
# TCSUPPORT_FIRST_IF_MT7615D is not set
# TCSUPPORT_FIRST_IF_MT7916N is not set
# TCSUPPORT_FIRST_IF_MT7916D is not set
# TCSUPPORT_FIRST_IF_MT7615_11AC is not set
TCSUPPORT_FIRST_IF_MT7915N=y
# TCSUPPORT_FIRST_IF_MT7915D is not set
# TCSUPPORT_SECOND_IF_NONE is not set
# TCSUPPORT_SECOND_IF_RT2561 is not set
# TCSUPPORT_SECOND_IF_RT3390 is not set
# TCSUPPORT_SECOND_IF_RT5392 is not set
# TCSUPPORT_SECOND_IF_RT5390 is not set
# TCSUPPORT_SECOND_IF_RT5390HL is not set
# TCSUPPORT_SECOND_IF_RT3090 is not set
# TCSUPPORT_SECOND_IF_MT7601E is not set
# TCSUPPORT_SECOND_IF_MT7592 is not set
# TCSUPPORT_SECOND_IF_MULTIDRIVER is not set
# TCSUPPORT_SECOND_IF_RT5592 is not set
# TCSUPPORT_SECOND_IF_RT3593 is not set
# TCSUPPORT_SECOND_IF_RT5592_RT3593 is not set
# TCSUPPORT_SECOND_IF_MT7610E is not set
# TCSUPPORT_SECOND_IF_MT7612E is not set
# TCSUPPORT_SECOND_IF_MT7613E is not set
# TCSUPPORT_SECOND_IF_MT7615_11N is not set
# TCSUPPORT_SECOND_IF_MT7615_11AC is not set
TCSUPPORT_SECOND_IF_MT7915E=y
# TCSUPPORT_CONFIG_FIRST_IF_EPAELNA is not set
TCSUPPORT_CONFIG_FIRST_IF_IPAILNA=y
# TCSUPPORT_CONFIG_FIRST_IF_IPAELNA is not set
# TCSUPPORT_CONFIG_FIRST_IF_EPAILNA is not set
# TCSUPPORT_CONFIG_SECOND_IF_EPAELNA is not set
TCSUPPORT_CONFIG_SECOND_IF_IPAILNA=y
# TCSUPPORT_CONFIG_SECOND_IF_IPAELNA is not set
# TCSUPPORT_CONFIG_SECOND_IF_EPAILNA is not set
TCSUPPORT_WLAN_MT7915N=y
TCSUPPORT_DUAL_WLAN_MT7915E=y
TCSUPPORT_WLAN_MT7992=y
# TCSUPPORT_WLAN_MT76_MAC80211 is not set
#
# USB
#
TCSUPPORT_USBHOST=y
TCSUPPORT_MUH=y
TCSUPPORT_USB_NTFS=y
# TCSUPPORT_USB_PRINTER_SERVER is not set
# TCSUPPORT_USB_3G_DONGLE is not set
# TCSUPPORT_USB_CAMERA is not set
TCSUPPORT_USB_HOST_LED=y
# end of USB

#
# Virtual Private Network(VPN) Support
#
TCSUPPORT_VPN=y
TCSUPPORT_HW_CRYPTO=y
# TCSUPPORT_EIP93_VERIFY is not set
# end of Virtual Private Network(VPN) Support

# TCSUPPORT_USBHOST is not set
TCSUPPORT_CMDAPI=y
TCSUPPORT_NAND_FLASH=y
# TCSUPPORT_EMMC_BLOCK is not set
TCSUPPORT_NEW_SPIFLASH=y
# TCSUPPORT_NOR_FLASH_USED is not set
# TCSUPPORT_NAND_BMT is not set
# TCSUPPORT_SPI_CONTROLLER_ECC is not set
# TCSUPPORT_NAND_FLASH_OTP is not set
# TCSUPPORT_SMUX is not set
TCSUPPORT_MT7570=y
TCSUPPORT_MT7572=y
TCSUPPORT_SEPERATED_ETH_ITF=y
TCSUPPORT_RA_HWNAT=y
TCSUPPORT_HWNAT_V3=y
# TCSUPPORT_HWNAT_L2VID is not set
TCSUPPORT_RA_HWNAT_ENHANCE_HOOK=y
TCSUPPORT_HWNAT_WAN_ACCOUNT=y
TCSUPPORT_ACCOUNT_METER_V2=y
# TCSUPPORT_UNKNOW_MULTICAST_COUNT is not set
TCSUPPORT_DS_HWNAT_OFFLOAD=y
TCSUPPORT_DLF_CTRL=y
# TCSUPPORT_FORWARD_LEFT_TO_RIGHT is not set
TCSUPPORT_GRE_TUNNEL_HWNAT=y
# TCSUPPORT_HWNAT_ADD_DEL_API is not set
# TCSUPPORT_L2TP_VPN_HWNAT is not set
# TCSUPPORT_DYING_GASP_OPTIMIZATION is not set
TCSUPPORT_QDMA_BUFMGR=y
# TCSUPPORT_MBUF_ENHANCE is not set
TCSUPPORT_MEMORY_CONTROL=y
TCSUPPORT_MAX_PACKET_2000=y
TCSUPPORT_ECNT_SKBMGR=y
# TCSUPPORT_UART_DISABLE is not set
# TCSUPPORT_UART2 is not set
# TCSUPPORT_FE_VIP_ENHANCEMENT is not set
TCSUPPORT_TSO_ENABLE=y
TCSUPPORT_LRO_ENABLE=y
# TCSUPPORT_LRO_FOR_SAMBA is not set
TCSUPPORT_IFC_EN=y
# TCSUPPORT_XSI_ENABLE is not set
# TCSUPPORT_WAN_XSI is not set
TCSUPPORT_ACTIVE_ETHERNET_WAN=y
TCSUPPORT_HSGMII_LAN=y
TCSUPPORT_ETHER_8811=y
TCSUPPORT_ETHER_8831=y
TCSUPPORT_ECNT_1588v2=y
TCSUPPORT_COMBO_PON=y
# TCSUPPORT_LAN_VLAN is not set
# TCSUPPORT_LAN_VLAN_RANGE is not set
# end of Driver Feature

# TCSUPPORT_WLAN is not set
TCSUPPORT_VOIP=y
TCSUPPORT_ECN_SIP=y
VOIP_MAX_CHAN=16
TCSUPPORT_VOIP_SRTP=y
TCSUPPORT_VOIP_RTCP_XR=y
#
# Passive Optical Network(PON) Support
#
TCSUPPORT_PON_SEL=y
TCSUPPORT_GPON_MAPPING=y
TCSUPPORT_GPON_DOWNSTREAM_MAPPING=y
TCSUPPORT_EPON_MAPPING=y
TCSUPPORT_PONMGR=y
TCSUPPORT_PMMGR=y
TCSUPPORT_XPON_IGMP=y
TCSUPPORT_PON_MAC_FILTER=y
TCSUPPORT_PON_USER_ISOLATION=y
TCSUPPORT_PON_VLAN=y
TCSUPPORT_PON_VLAN_FILTER=y
# TCSUPPORT_VLAN_PASSTHROUGH is not set
# TCSUPPORT_ETHER_DOWNVLAN is not set
TCSUPPORT_PON_IP_HOST=y
TCSUPPORT_XPON_LED=y
# TCSUPPORT_XPON_LED_UPGRADE is not set
# TCSUPPORT_PON_TEST is not set
# TCSUPPORT_PON_FH is not set
# TCSUPPORT_EPON_DUMMY is not set
# TCSUPPORT_GPON_GREENDROP_OPEN is not set
# TCSUPPORT_PON_SFU_HGU_HYBRID is not set
# TCSUPPORT_XPON_HYBIRD is not set
TCSUPPORT_OMCI=y
TCSUPPORT_OMCI_EXTENDED_MSG=y
TCSUPPORT_OMCI_CTC=y
TCSUPPORT_OMCI_DOT1AG=y
TCSUPPORT_HGU_OMCI_MIB_UPLOAD_PPTP_ETH_UNI=y
TCSUPPORT_OMCI_LAN_DEBUG=y
# TCSUPPORT_OMCI_ALCATEL is not set
# TCSUPPORT_HUAWEI_OLT_VENDOR_SPECIFIC_ME is not set
TCSUPPORT_EPON_OAM=y
TCSUPPORT_EPON_OAM_CTC=y
TCSUPPORT_EPON_OAM_LAN_DBG=y
# TCSUPPORT_EPON_FPGA_WORKAROUND is not set
# TCSUPPORT_EPONCMD is not set
TCSUPPORT_EPON_ATTACK_ENHANCE=y
# end of Passive Optical Network(PON) Support

#
# Common Feature
#
BSP=y
TCSUPPORT_DUAL_IMAGE=y
TCSUPPORT_GPON_DUAL_IMAGE=y
TCSUPPORT_EPON_DUAL_IMAGE=y
# TCSUPPORT_SDN_OVS is not set
# TCSUPPORT_UBIFS is not set
TCSUPPORT_L2OGRE=y
TCSUPPORT_IPV6=y

#
# IPv6 Support
#
TCSUPPORT_IPV6_ENHANCEMENT=y
TCSUPPORT_MLD_SNOOPING=y
TCSUPPORT_MLD_PROXY=y
# TCSUPPORT_IPV6_CEROUTER is not set
TCSUPPORT_DSLITE=y
# TCSUPPORT_6RD is not set
TCSUPPORT_IPV6_ADVANCE=y
# TCSUPPORT_IPV6_ACL is not set
TCSUPPORT_IPV6_FIREWALL=y
# TCSUPPORT_IPV6_RIPNG is not set
TCSUPPORT_IPV6_TELNET=y
TCSUPPORT_IPV6_TFTP=y
TCSUPPORT_IPV6_FTP=y
TCSUPPORT_IPV6_INETD=y
# end of IPv6 Support

TCSUPPORT_QOS=y
# TCSUPPORT_DOWNSTREAM_QOS is not set
TCSUPPORT_IGMP_QOS=y
# TCSUPPORT_QOS_QUEUE_MODIFY is not set
TCSUPPORT_QOS_EIGHT_QUEUE=y
# TCSUPPORT_SWNAT is not set
# TCSUPPORT_TLS is not set
# TCSUPPORT_SOFT_RATELIMIT is not set
# TCSUPPORT_VLAN_TAG is not set
# TCSUPPORT_PORTBIND is not set
TCSUPPORT_BRIDGE_MAC_LIMIT=y
# TCSUPPORT_WAN2LAN_EXT is not set
TCSUPPORT_ORN_EBTABLES=y
TCSUPPORT_IGMP_PROXY=y
# TCSUPPORT_IGMP_PROXY_V3 is not set
TCSUPPORT_IGMP_SNOOPING=y
TCSUPPORT_IGMPSNOOPING_ENHANCE=y
TCSUPPORT_IGMP_QUICK_LEAVE=y
# TCSUPPORT_IGMP_SNOOPING_V3 is not set
# TCSUPPORT_SNOOPING_SEPERATION is not set
TCSUPPORT_MULTICAST_SPEED=y
TCSUPPORT_MULTI_USER_ITF=y
# TCSUPPORT_MTD_PARTITIONS_CMDLINE is not set
# TCSUPPORT_PARTITIONS_CMDLINE_STR is not set
TCSUPPORT_MTD_PARTITION_NUM=9
TCSUPPORT_MTD_ENCHANCEMENT=y
TCSUPPORT_RESERVEAREA_BLOCK=14
TCSUPPORT_RESERVEAREA_EXTEND=y
TCSUPPORT_QDMA_WAN_DSCP_NUM=4
TCSUPPORT_QDMA_LAN_DSCP_NUM=1
TCSUPPORT_BACKUPROMFILE=y
# TCSUPPORT_PRODUCTIONLINE is not set
TCSUPPORT_PROLINECMD_NG=y
# TCSUPPORT_MULTICAST_BSP_GENERAL is not set
# TCSUPPORT_CODE_SHRINK is not set
# TCSUPPORT_LED_BTN_CHECK is not set
# TCSUPPORT_TEST_LED_ALL is not set
# TCSUPPORT_WAN_ETHER_LED is not set
# TCSUPPORT_MANUAL_ETHERNET_PORTMAP is not set
# TCSUPPORT_MEMORY_SHRINK is not set
TCSUPPORT_MEMORY_SHRINK_V2=y
TCSUPPORT_NEW_WDOG=y
# TCSUPPORT_VLAN_ACCESS_TRUNK is not set
TCSUPPORT_USER_DEFINE_FIRST_MAC=-1
TCSUPPORT_NPTv6=y
# TCSUPPORT_VXLAN is not set
# end of Common Feature
# TCSUPPORT_CT_LOOPDETECT is not set
TCSUPPORT_OPENWRT=y
TCSUPPORT_SISM=y
TCSUPPORT_SISM_HOST=y
TCSUPPORT_HOST_SERVICE_MANAGER=y
TCSUPPORT_BRIDGE_MAC_LIMIT=y

# L4S Support
TCSUPPORT_L4S=y
ARHT_SECURE_CFLAGS=y

# iopsys changes
TCSUPPORT_IOPSYS_DISABLE_IPV6_DEV_CONFIG_ECNT_HOOK=y

TCSUPPORT_NEW_SPI=y
