#!/bin/sh /etc/rc.common

START=11

. /usr/share/libubox/jshn.sh
. /lib/functions.sh

NEED_AE_WAN=
NEED_HSGMII_LAN=
HSGMII_PORTS=
PON_PHY_CONFLICT=

check_2_5g_lan_port() {
	local interface="$1"
	case "$interface" in
	eth[0-9] | eth[0-9][0-9])
		NEED_HSGMII_LAN=1
		if [ -z "$HSGMII_PORTS" ]; then
			HSGMII_PORTS="$interface"
		else
			HSGMII_PORTS="$HSGMII_PORTS $interface"
		fi
	esac
}

boot() {
	PROFILE_CFG=/userfs/profile.cfg
	if [ -f $PROFILE_CFG ] ; then
	    . $PROFILE_CFG
	fi

	echo "mknod /dev/ipsec c 266 0"
	mknod /dev/ipsec c 266 0

	echo "mknod /dev/hwnat0 c 220 0"
	mknod /dev/hwnat0 c 220 0

	echo "mknod /dev/qdma_lan c 119 0"
	mknod /dev/qdma_lan c 119 0

	echo "mknod /dev/qdma_wan c 120 0"
	mknod /dev/qdma_wan c 120 0

	echo "mknod /dev/fe c 226 0"
	mknod /dev/fe c 226 0

	echo "mknod /dev/serdes_cfg c 267 0"
	mknod /dev/serdes_cfg c 267 0

	echo "mknod /dev/pon c 190 0"
	mknod /dev/pon c 190 0

	echo "mknod /dev/xponmap c 210 0"
	mknod /dev/xponmap c 210 0

	echo "mknod /dev/ponvlan c 215 0"
	mknod /dev/ponvlan c 215 0

	echo "mknod /dev/ponmacfilter c 216 0"
	mknod /dev/ponmacfilter c 216 0

	echo "mknod /dev/xponigmp c 185 0"
	mknod /dev/xpon_igmp c 185 0

	if [ "$TCSUPPORT_CPU_EN7523" != "" ]; then
		echo "mknod /dev/gponflow c 184 0"
		mknod /dev/gpon_flow c 184 0
	fi

	echo "mknod /dev/epon_mac c 221 0"
	mknod /dev/epon_mac c 221 0

	echo "mknod /dev/ifc c 241 0"
	mknod /dev/ifc c 241 0

	echo "mknod /dev/bbf247 c 268 0"
	mknod /dev/bbf247 c 268 0

	echo "mknod /dev/ivi c 269 0"
	mknod /dev/ivi c 269 0

	echo "mknod /dev/hsgmii_lan0 c 290 0"
	mknod /dev/hsgmii_lan0 c 290 0

	echo "mknod /dev/dpoe_service c 280 0"
	mknod /dev/dpoe_service c 280 0

	if [ -f /etc/board.json ]; then
		json_init
		json_load_file /etc/board.json
		json_select network
		json_select wan 2>/dev/null
		json_get_var wan_device device
		[ $wan_device == "ae_wan" ] && NEED_AE_WAN=1
		json_select ..
		json_select lan
		if json_is_a ports array; then
			json_for_each_item check_2_5g_lan_port ports
		else
			json_get_var lan_device device
			[ -n "$lan_device" ] && check_2_5g_lan_port "$lan_device"
		fi
		json_select ..
		json_cleanup
	fi

	# AE WAN conflicts with PON PHY in case of PON serdes
	if [ "$NEED_AE_WAN" = "1" ]; then
		PON_PHY_CONFLICT=1
	fi

	if [ "$TCSUPPORT_CPU_EN7523" = "" ]; then
		if [ "$PON_PHY_CONFLICT" = "" ]; then
			echo "insmod xpon_hal.ko"
			insmod /lib/modules/5.4.55/xpon_hal.ko
		fi

		echo "insmod ipsec.ko"
		insmod /lib/modules/5.4.55/ipsec.ko

		if [ "$PON_PHY_CONFLICT" = "" ]; then
			echo "insmod econet-xpon_int.ko"
			insmod /lib/modules/5.4.55/xpon_int.ko
		fi

		CHIPID=`cat /proc/tc3162/chip_id`
		DSLFLAG=`cat /proc/tc3162/wan_type | sed -n '3p' | sed 's/^.*DSL=//g' | sed 's/[ \t]*$//g'`
		GPIO_7517=`cat /proc/tc3162/rst_gpio | awk -F ',' '{print $1}'`

		if [ "$GPIO_7517" == "-1" ]; then
			GPIO_7517=39
		fi

		XPONMODE=`cat /proc/xpon_int/get_onu_mode`
		COMBOENABLE=`cat /proc/xpon_int/combo_enable`
		COMBOFLAG=`cat /proc/xpon_int/combo`

		if [ "$XPONMODE" = "1" ] || [[ "$XPONMODE" = "0" && "$CHIPID" = "59" ]]; then
			BOB_MODULE_OPTS="dualbob=7570"
			PHY_MODULE=phy_10g.ko
			LDDA_MODULE=en7571.ko
			XPON_MODULE=xpon.ko
			XPON_MODULE_OPTS=""
		else
			BOB_MODULE_OPTS="dualbob=7572"
			PHY_MODULE=phy_10g.ko
			LDDA_MODULE=en7572.ko
			XPON_MODULE=xpon_10g.ko
			XPON_MODULE_OPTS=""
		fi
	else
		onu_type=$(cmdline_get_var onu_type) #1:SFU, 2:HGU
		[ "$onu_type" == "1" ] || onu_type=2 #default to HGU

		BOB_MODULE_OPTS=""
		PHY_MODULE=phy.ko
		LDDA_MODULE=""
		XPON_MODULE=xpon.ko
		XPON_MODULE_OPTS="onu_type=${onu_type}"
	fi

	echo "insmod econet-bob.ko"
	#insmod /lib/modules/5.4.55/econet_bob.ko ${BOB_MODULE_OPTS}
	# econet_bob.ko destroys the BOSA calibration data when unloaded; DO NOT USE!
	ecnt_sys get bob ${BOB_MODULE_OPTS#*=}

	if [ "$PON_PHY_CONFLICT" = "" ]; then
		echo "insmod econet-xpon_${PHY_MODULE}"
		insmod /lib/modules/5.4.55/${PHY_MODULE}
	fi

	if [ "$NEED_HSGMII_LAN" = "1" ]; then
		echo "insmod hsgmii_lan.ko"
		insmod /lib/modules/5.4.55/hsgmii_lan.ko
	fi

	# AE WAN conflicts with PON modules
	if [ -f "/proc/tc3162/wan_2_5" -o "$NEED_AE_WAN" = "1" ]; then
		echo "insmod ae_wan"
	else
		if [ -n "${LDDA_MODULE}" ]; then
			if [ "$TCSUPPORT_CPU_EN7523" = "" ]; then
				echo "insmod an8901.ko"
				insmod /lib/modules/5.4.55/an8901.ko
			fi
			echo "insmod econet-${LDDA_MODULE}"
			insmod /lib/modules/5.4.55/${LDDA_MODULE}
		fi

		echo "insmod econet-${XPON_MODULE}"
		insmod /lib/modules/5.4.55/${XPON_MODULE} ${XPON_MODULE_OPTS}

		if [ "$TCSUPPORT_CPU_EN7581" = "" ]; then
			echo "insmod econet-xpon_int.ko"
			insmod /lib/modules/5.4.55/xpon_int.ko
		fi

		echo "insmod econet-xpon_map.ko"
		insmod /lib/modules/5.4.55/xponmap.ko

		echo "uni_num 4" > /proc/gponmap/port_info
		if [ "$NEED_HSGMII_LAN" = "1" ]; then
			IDX=5
			for HSGMII_PORT in $HSGMII_PORTS; do
				echo "uni_num ${IDX}" > /proc/gponmap/port_info
				echo "${IDX} dev_name ${HSGMII_PORT}" > /proc/gponmap/port_info
				echo "${IDX} unit_type 49" > /proc/gponmap/port_info
				IDX=$((IDX+1))
			done
		fi

		echo "insmod econet-pon_vlan.ko"
		insmod /lib/modules/5.4.55/ponvlan.ko

		if [ "$TCSUPPORT_PON_SFU_HGU_HYBRID" != "" ]; then
			echo "insmod econet-gpon_igmp.ko"
			insmod /lib/modules/5.4.55/gpon_igmp.ko
		else
			echo "insmod econet-xpon_igmp.ko"
			insmod /lib/modules/5.4.55/xpon_igmp.ko
		fi

		if [ "$TCSUPPORT_CPU_EN7523" != "" ]; then
			echo "insmod econet-gpon_flow.ko"
			insmod /lib/modules/5.4.55/gpon_flow.ko
		fi

		echo "insmod econet-ponmacfilter.ko"
		insmod /lib/modules/5.4.55/ponmacfilter.ko

		echo "insmod dpoe_service.ko"
		insmod /lib/modules/5.4.55/dpoe_service.ko

		echo " echo 1 > /proc/sys/net/ipv4/ip_forward"
		echo 1 > /proc/sys/net/ipv4/ip_forward

		echo "touch /tmp/.xponconfig"
		touch /tmp/.xponconfig

		echo "ifconfig pon up"
		ifconfig pon up

		echo "ifconfig omci up"
		ifconfig omci up
	fi
}
