#!/bin/sh /etc/rc.common

START=11
STOP=99
USE_PROCD=1

. /lib/functions/system.sh


start_service() {
	readonly need_xdsl="$(jsonfilter -i /etc/board.json -e @.dsl)"
	readonly wanport="$(jsonfilter -i /etc/board.json -e @.network.wan.device)"

	local macserno="$(macaddr_setbit_la "$(get_mac_label)" | tr -d ':' | tr 'a-z' 'A-Z')"
	local reset_gpio=""
	local reset_chip=""
	local wan_intf="nas10"

	[ -f /etc/board.json ] || return 0

	if [ "$need_xdsl" != "" ]; then
		reset_gpio="$(gpiofind HW_RST_N_7517 | cut -f2 -d' ')"
		reset_chip="$(gpiofind HW_RST_N_7517 | cut -f1 -d' ')"
		reset_chip="${reset_chip/gpiochip}"

		if [ -n "$reset_gpio" -a -n "$reset_chip" ]; then
			reset_chip=$((reset_chip*32))
			reset_gpio=$((reset_gpio+reset_chip))
		else
			reset_gpio=30
		fi

		if [ -f /proc/device-tree/ae_wan/wan-dsl ]; then
			# Load AE WAN kernel module
			echo "insmod ae_wan.ko"
			insmod /lib/modules/5.4.55/ae_wan.ko

			[ -f /proc/tc3162/ae_wan_inic_filter ] && echo enable > /proc/tc3162/ae_wan_inic_filter
			if [ -f /proc/tc3162/ae_wan_mac_dbg ]; then
				echo fc tx 1 > /proc/tc3162/ae_wan_mac_dbg
				echo fc rx 1 > /proc/tc3162/ae_wan_mac_dbg
			fi

			wan_intf="ae_wan"
		fi

		if [ "$wanport" != "$wan_intf" ]; then
			ifconfig "$wan_intf" mtu 1982
		fi
		ifconfig "$wan_intf" down up

		echo "insmod en7517_host_sar.ko"
		insmod /lib/modules/5.4.55/en7517_host_sar.ko ethwan="$wan_intf"

		# Set vlan mode to EN7517 for ATM
		[ -f /proc/tc3162/single_vlan_mode ] && echo 0 > /proc/tc3162/single_vlan_mode
		[ -f /proc/tc3162/adsl_mpoa_header ] && echo 1 > /proc/tc3162/adsl_mpoa_header
		[ -f /proc/tc3162/tsarm_mpoa_header ] && echo 0 > /proc/tc3162/tsarm_mpoa_header

		echo "insmod client_info.ko"
		insmod client_info devName="$wan_intf"

		procd_open_instance hsm
		procd_set_param command /userfs/bin/hsm "$wan_intf" "$reset_gpio" 24 "$macserno" 0
		procd_set_param respawn
		procd_set_param stdout 1
		procd_close_instance
	fi
}
