#
# Automatically generated make config: don't edit
# Thu Nov 18 23:31:45 2021
#

# TCSUPPORT_CPU_EN7528 is not set
# TCSUPPORT_CPU_EN7580 is not set
TCSUPPORT_CPU_EN7523=y
# TCSUPPORT_KERNEL is not set
# TCSUPPORT_4_4_KERNEL is not set
TCSUPPORT_5_4_KERNEL=y
WAN_ETHER=y
WAN_GPON=y
WAN_EPON=y

#
# WAN Transfer Mode Support
#

#
# At Least One of The Following Has to Be Chosen!
#
TCSUPPORT_WAN_ETHER=y
# TCSUPPORT_QDMA_WAN_FOR_ETHER is not set
TCSUPPORT_WAN_GPON=y
TCSUPPORT_WAN_EPON=y
TCSUPPORT_BOOT_LZMA=y
TCSUPPORT_DDR_CALI=y
TCSUPPORT_BOOTROM_LARGE_SIZE=y
# TCSUPPORT_KERNELCONFIG_EN7527 is not set
# TCSUPPORT_KERNELCONFIG_EN7528 is not set
# TCSUPPORT_KERNELCONFIG_EN7580 is not set
TCSUPPORT_KERNELCONFIG_EN7523=y

#
# Driver Feature
#
TCSUPPORT_SISM=y
TCSUPPORT_SISM_HOST=y
TCSUPPORT_HOST_SERVICE_MANAGER=y
TCSUPPORT_DUAL_IMAGE=y
TCSUPPORT_GPON_DUAL_IMAGE=y
TCSUPPORT_EPON_DUAL_IMAGE=y
TCSUPPORT_NPU=y
TCSUPPORT_MT7520_PCIE=y
TCSUPPORT_I2C=y
TCSUPPORT_WLAN=y
TCSUPPORT_WLAN_8021X=y
TCSUPPORT_WLAN_WPS=y
TCSUPPORT_WLAN_WDS=y
TCSUPPORT_WLAN_IGMPSNOOP=y
TCSUPPORT_HTBW_40M=y
TCSUPPORT_WLAN_ATE=y
TCSUPPORT_WLAN_QATOOL=y
TCSUPPORT_WLAN_WPS_LEDSPEC=y
TCSUPPORT_WLAN_MULTI_WPS=y
TCSUPPORT_WLAN_GPIO=y
# TCSUPPORT_WLAN_LED_BY_SW is not set
TCSUPPORT_WLAN_PERSSID_SWITCH=y
TCSUPPORT_WLAN_PMF=y
TCSUPPORT_WLAN_TXBF=y
TCSUPPORT_EEPROM_ACEXT=y
# TCSUPPORT_WLAN_MT7915_BUILD_IN is not set
TCSUPPORT_WLAN_WPA3=y
TCSUPPORT_WLAN_AX=y
TCSUPPORT_FIRST_IF_MT7915D=y
TCSUPPORT_SECOND_IF_NONE=y
TCSUPPORT_CONFIG_FIRST_IF_IPAILNA=y
TCSUPPORT_WLAN_MT7915D=y
TCSUPPORT_WLAN_MT76_MAC80211=y

#
# Virtual Private Network(VPN) Support
#
TCSUPPORT_VPN=y
TCSUPPORT_HW_CRYPTO=y
TCSUPPORT_USBHOST=y
TCSUPPORT_MUH=y
TCSUPPORT_USB_NTFS=y
TCSUPPORT_USB_AUTOMOUNT=y
TCSUPPORT_USB_HOST_LED=y
TCSUPPORT_NAND_FLASH=y
TCSUPPORT_MT7570=y
NOT_SUPPORT_BADBLOCK_CHECK=y
# TCSUPPORT_NAND_BMT is not set
TCSUPPORT_RA_HWNAT=y
TCSUPPORT_HWNAT_V3=y
TCSUPPORT_RA_HWNAT_ENHANCE_HOOK=y
# TCSUPPORT_HWNAT_WAN_ACCOUNT is not set
TCSUPPORT_DS_HWNAT_OFFLOAD=y
TCSUPPORT_DLF_CTRL=y
TCSUPPORT_QDMA_BUFMGR=y
TCSUPPORT_OMCI=y
TCSUPPORT_OMCI_EXTENDED_MSG=y
TCSUPPORT_OMCI_CTC=y
TCSUPPORT_OMCI_DOT1AG=y
TCSUPPORT_HGU_OMCI_MIB_UPLOAD_PPTP_ETH_UNI=y
TCSUPPORT_OMCI_LAN_DEBUG=y
TCSUPPORT_EPON_OAM=y
TCSUPPORT_EPON_OAM_CTC=y
TCSUPPORT_EPON_OAM_LAN_DBG=y
# TCSUPPORT_UART2 is not set
# TCSUPPORT_SPI_CONTROLLER_ECC is not set
# TCSUPPORT_GRE_TUNNEL_HWNAT is not set
# TCSUPPORT_NPU_TUNNEL_OFFLOAD is not set

#
# Common Feature
#
TCSUPPORT_CPU_ARMV8=y
# TCSUPPORT_CPU_ARMV8_64 is not set
TCSUPPORT_UBOOT=y
TCSUPPORT_UBOOT_2014=y
TCSUPPORT_ATF_2_1=y

#
# Passave Optical Network(PON) Support
#
TCSUPPORT_PON_SEL=y
TCSUPPORT_MAX_PACKET_2000=y
TCSUPPORT_GPON_MAPPING=y
TCSUPPORT_GPON_DOWNSTREAM_MAPPING=y
TCSUPPORT_EPON_MAPPING=y
TCSUPPORT_PONMGR=y
TCSUPPORT_PMMGR=y
TCSUPPORT_XPON_IGMP=y
TCSUPPORT_PON_MAC_FILTER=y
TCSUPPORT_PON_USER_ISOLATION=y
TCSUPPORT_PON_VLAN=y
TCSUPPORT_PON_VLAN_FILTER=y
TCSUPPORT_PON_IP_HOST=y
TCSUPPORT_XPON_LED=y
TCSUPPORT_IPV6=y
TCSUPPORT_IPV6_ENHANCEMENT=y
TCSUPPORT_DSLITE=y
# TCSUPPORT_6RD is not set
TCSUPPORT_IPV6_ADVANCE=y
TCSUPPORT_TSO_ENABLE=y
TCSUPPORT_TSO_V2_ENABLE=y 
# TCSUPPORT_LRO_ENABLE is not set
TCSUPPORT_ACTIVE_ETHERNET_WAN=y
TCSUPPORT_HSGMII_LAN=y
TCSUPPORT_VOIP=y

#
# CUSTOMIZE VOIP menu
#
TCSUPPORT_ECN_SIP=y
TCSUPPORT_ECN_MEGACO=y
VOIP_MAX_CHAN=8
TCSUPPORT_QOS=y
TCSUPPORT_IGMP_QOS=y
TCSUPPORT_SWNAT=y
TCSUPPORT_SEPERATED_ETH_ITF=y
TCSUPPORT_MLD_SNOOPING=y
TCSUPPORT_MLD_PROXY=y
TCSUPPORT_IGMP_PROXY_V3=y
TCSUPPORT_IGMP_SNOOPING=y
TCSUPPORT_IGMPSNOOPING_ENHANCE=y
TCSUPPORT_MULTICAST_SPEED=y
# TCSUPPORT_MTD_PARTITIONS_CMDLINE is not set
# TCSUPPORT_PARTITIONS_CMDLINE_STR is not set
TCSUPPORT_MTD_PARTITION_NUM=9
TCSUPPORT_MTD_ENCHANCEMENT=y
TCSUPPORT_RESERVEAREA_BLOCK=6
TCSUPPORT_QDMA_WAN_DSCP_NUM=4
TCSUPPORT_QDMA_LAN_DSCP_NUM=1
TCSUPPORT_LED_BTN_CHECK=y
TCSUPPORT_BTN_CHECK=y
TCSUPPORT_TEST_LED_ALL=y
TCSUPPORT_NEW_SPIFLASH=y

#
# Ethernet Port Mapping to Switch Port
#
TCSUPPORT_EPON_ATTACK_ENHANCE=y
# TCSUPPORT_DNSBIND_DEV is not set
TCSUPPORT_NEW_WDOG=y
TCSUPPORT_HIGHMEM=y
TCSUPPORT_IFC_EN=y
TCSUPPORT_ECNT_SKBMGR=y
TCSUPPORT_USER_DEFINE_FIRST_MAC=-1
TCSUPPORT_WLAN_AC=y
TCSUPPORT_NPTv6=y
TCSUPPORT_ORN_EBTABLES=y
#
# Customer feature
#
TCSUPPORT_IGMP_PROXY=y
TCSUPPORT_IGMP_QUICK_LEAVE=y
TCSUPPORT_VIR_SERVER=y
TCSUPPORT_IMPROVE_GUI_PERFM=y
TCSUPPORT_RESERVEAREA_EXTEND=y
TCSUPPORT_MULTI_USER_ITF=y
TCSUPPORT_BLAPI=y

#
# Beta feature: Parallel Build
#
# TCSUPPORT_PARALLEL_BUILD_KERNEL_OFF is not set
# TCSUPPORT_PARALLEL_BUILD_CUSTOM_JOB_NUM_ENABLE is not set
BSP=y
TCSUPPORT_OPENWRT=y
TCSUPPORT_ARM_SECURE_BOOT=y

# iopsys changes
TCSUPPORT_NP=y
TCSUPPORT_NPU_WIFI_OFFLOAD=y
TCSUPPORT_QOS_EIGHT_QUEUE=y
TCSUPPORT_IOPSYS_DISABLE_IPV6_DEV_CONFIG_ECNT_HOOK=y
TCSUPPORT_BRIDGE_MAC_LIMIT=y
