define release_bindir_gen
	$$(echo $(1) | sed 's|$(TRUNK_DIR)|$(BIN_BAK_PATH)|')/$(TCPLATFORM)
endef

ifneq ($(strip $(TCSUPPORT_OPENWRT)),)
#include $(INCLUDE_DIR)/kernel.mk
#include $(INCLUDE_DIR)/ecnt-trunkdir.mk
#-include $(KERNEL_BUILD_DIR)/BSP/xpon_bsp/xpon_dir.mak
MODULES_ALL_QDMA_DIR=$(MODULES_PRIV_SRC_DIR)/qdma
export MODULES_ALL_QDMA_DIR
#GLOBAL_INC_DIR=$(TRUNK_DIR)/linux-4.4.115/include/global_inc
#BOOTROM_DIR=$(PKG_BUILD_DIR)/src
#KERNEL_ECNT_DIR=$(TRUNK_DIR)/linux-4.4.115/
else
TRUNK_DIR=$(shell pwd)
export TRUNK_DIR
CUSKIT_DIR=$(TRUNK_DIR)/cuskit_tclinux
export CUSKIT_DIR
BIN_BAK_PATH=$(TRUNK_DIR)
export BIN_BAK_PATH
GLOBAL_INC_DIR=$(TRUNK_DIR)/global_inc
endif
ifneq ($(strip $(TCSUPPORT_UBOOT)),)
BOOTROM_DIR=$(TRUNK_DIR)/bootloader
BOOTROM_UNOPEN_DIR=$(TRUNK_DIR)/bootloader_unopen
UBOOT_DIR=$(BOOTROM_DIR)/Uboot
export UBOOT_DIR
ATF_DIR=$(BOOTROM_DIR)/ATF
export ATF_DIR
ATF_UNOPEN_DIR=$(BOOTROM_UNOPEN_DIR)/ATF
export ATF_UNOPEN_DIR
else
BOOTROM_DIR=$(TRUNK_DIR)/bootrom
endif

ifneq ($(strip $(TCSUPPORT_OPTEE)),)
OPTEE_DIR=$(BOOTROM_DIR)/optee_os-3.21.0
endif

ifneq ($(strip $(TCSUPPORT_6_6_KERNEL)),)
KERNEL_ECNT_DIR=$(TRUNK_DIR)/linux-arht-sdk
else
KERNEL_ECNT_DIR=$(TRUNK_DIR)/linux-ecnt
endif

export GLOBAL_INC_DIR
GLOBAL_FLASH_LAYOUT_INC_DIR=$(GLOBAL_INC_DIR)/flash_layout
export GLOBAL_FLASH_LAYOUT_INC_DIR
PROJECT_DIR=$(TRUNK_DIR)/Project
IMAGE_DIR=$(PROJECT_DIR)/images
export IMAGE_DIR
PROJECT_MENUCONFIG_DIR=$(PROJECT_DIR)/config/menuconfig
PROJECT_AUTOCONFIG_DIR=$(PROJECT_DIR)/config/autoconfig
PROJECT_LIB_DIR=$(PROJECT_DIR)/lib
PROJECT_LIB_DIR_ARM64_LIB=$(PROJECT_LIB_DIR)/arm64-gcc910-glibc229-lib
ifneq ($(strip $(CUSTOM)),)
PROFILE_DIR=$(PROJECT_DIR)/profile/$(CUSTOM)/$(PROFILE)
else
PROFILE_DIR=$(PROJECT_DIR)/profile/$(PROFILE)
endif
export PROFILE_DIR
SRCFS_DIR=$(PROFILE_DIR)/fs.src
export BOOTROM_DIR
BOOTROM_UNOPEN_IMG_DIR=$(BOOTROM_DIR)/unopen_img
export BOOTROM_UNOPEN_IMG_DIR
export IS_BOOTROM_DIR_EXIST=$(if $(wildcard $(BOOTROM_DIR)/.),Y,N)
FT_DIR=$(TRUNK_DIR)/bootrom_ft
APP_DIR=$(TRUNK_DIR)/apps
APP_PRIVATE_DIR=$(APP_DIR)/private
APP_BSP_DIR=$(TRUNK_DIR)/app_bsp
APP_BSP_PRIVATEDIR=$(APP_BSP_DIR)/private
APP_BSP_PUBLICDIR=$(APP_BSP_DIR)/public

EXPORT_BSP_DIR=$(KERNEL_BUILD_DIR)/install_bsp
INSTALL_BSP_DIR=$(EXPORT_BSP_DIR)
export LIB_INSTALL_DIR=$(EXPORT_BSP_DIR)/bsp_install
APP_BSP_LIB_DIR=$(LIB_INSTALL_DIR)
export LIB_DIR=$(LIB_INSTALL_DIR) 
# export BSP_EXT_MAKE=$(EXPORT_BSP_DIR)/make
export BSP_EXT_TCLINUX_BUILDER=$(LIB_INSTALL_DIR)/tclinux_builder
# export BSP_EXT_TOOLS=$(EXPORT_BSP_DIR)/tools
export INSTALL_KERNELHEADER=$(EXPORT_BSP_DIR)/kernel_header
export INSTALL_GLOBALINC=$(EXPORT_BSP_DIR)/global_inc_install
export INSTALL_DEVGEN_DIR=$(LIB_INSTALL_DIR)/devgen
export INSTALL_XPON_DIR=$(LIB_INSTALL_DIR)/xpon


export BSP_EXT_DIR=$(EXPORT_BSP_DIR)/bsp_external
export BSP_EXT_INSTALL=$(BSP_EXT_DIR)


export BSP_EXT_INC=$(BSP_EXT_DIR)/inc
export BSP_EXT_FS=$(BSP_EXT_DIR)/fs
export BSP_EXT_LIB=$(BSP_EXT_FS)/lib
export BSP_EXT_MODULE=$(BSP_EXT_LIB)/modules
export BSP_EXT_FS_BIN=$(BSP_EXT_FS)/bin
export BSP_EXT_FS_USR=$(BSP_EXT_FS)/usr/bin
export BSP_EXT_FS_USEFS_DIR=$(BSP_EXT_FS)/userfs
export BSP_EXT_FS_USEFS=$(BSP_EXT_FS)/userfs/bin

export APP_BSP_LIB_DIR
APP_BSP_API_DIR=$(APP_BSP_DIR)/API
export APP_BSP_API_DIR
export BSP_API_SW_API_DIR=$(BSP_API_DIR)/sw_api
export BSP_API_HW_DRIVER_DIR=$(BSP_API_DIR)/hw_driver
export BSP_BLAPI_DIR=$(BSP_API_DIR)/ecnt_blapi
APP_BSP_API_MTK_ITF_DIR=$(APP_BSP_API_DIR)/mtk_itf
APP_BSP_API_MTK_ITF_QOS_DIR = $(APP_BSP_API_MTK_ITF_DIR)/mtk_itf_qos
APP_BSP_API_MTK_ITF_SWITCH_DIR = $(APP_BSP_API_MTK_ITF_DIR)/mtk_itf_switch
APP_BSP_API_MTK_ITF_FE_DIR=$(APP_BSP_API_MTK_ITF_DIR)/mtk_itf_fe
APP_BSP_API_MTK_ITF_SIMULATION_DIR=$(APP_BSP_API_MTK_ITF_DIR)/mtk_itf_simulation
APP_BSP_API_MTK_ITF_PPE_DIR=$(APP_BSP_API_MTK_ITF_DIR)/mtk_itf_ppe

APP_BSP_EXCLUSIVE_DIR=$(APP_BSP_DIR)/private_exclusive
APP_BSP_BUILD_DIR=$(APP_BSP_EXCLUSIVE_DIR)/bsp_builder
export APP_BSP_BUILD_DIR
APP_BSP_EXCLUSIVE_PUBLIC_DIR=$(APP_BSP_DIR)/public_exclusive
APP_BSP_EXCLUSIVE_PUBLIC_8021X_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/8021X
APP_BSP_EXCLUSIVE_PRIVATE_DIR=$(APP_BSP_DIR)/private_exclusive
APP_BSP_BUSYBOX_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/busybox-1.26.2
APP_BSP_PPPD_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/ppp-2.4.7
APP_BSP_BRCTL_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/bridge-utils-1.5
APP_BSP_IPTABLES_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/iptables-1.6.1
APP_BSP_IPTABLES_INSTALL_DIR=$(APP_BSP_IPTABLES_DIR)/install
APP_BSP_BR2684_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/br2684ctl
APP_BSP_LINUX_ATM_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/linux-atm
APP_BSP_WRIELESSTOOL_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/wireless_tools.28
ECNT_EVENT_LIB_DIR=$(APP_BSP_API_DIR)/ecnt_event
APP_BSP_MXML_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/mxml-2.4
APP_OMCI_DEMO_DIR=$(APP_BSP_EXCLUSIVE_PRIVATE_DIR)/omci_demo
APP_BSP_TCCI_DIR=$(APP_BSP_EXCLUSIVE_PRIVATE_DIR)/tcci_bsp
APP_BSP_TCCI_COMMON_DIR=$(APP_BSP_PRIVATEDIR)/tcci_common
APP_BSP_ATED_DIR=$(APP_BSP_EXCLUSIVE_PRIVATE_DIR)/ATED
APP_BSP_11KV_DIR=$(APP_BSP_EXCLUSIVE_PRIVATE_DIR)/11kv_test_daemon
APP_BSP_BNDSTRG_DIR=$(APP_BSP_EXCLUSIVE_PRIVATE_DIR)/bndstrg_plus
APP_BSP_WLANCMD_DIR=$(APP_BSP_EXCLUSIVE_PRIVATE_DIR)/wlancmd
APP_BSP_TCWDOG_DIR=$(APP_BSP_EXCLUSIVE_PRIVATE_DIR)/tcwdog
APP_BSP_SMUX_DIR=$(APP_BSP_EXCLUSIVE_PRIVATE_DIR)/smuxctl
APP_BSP_ETHCMD_DIR=$(APP_BSP_PRIVATEDIR)/ethcmd
APP_BSP_BUTTONS_DIR=$(APP_BSP_PRIVATEDIR)/buttons
APP_BSP_ETHTOOL_DIR=$(APP_BSP_PRIVATEDIR)/ethtool
APP_BSP_RA_HWNAT_7510_DIR=$(APP_BSP_PRIVATEDIR)/hw_nat_7510
APP_BSP_CHIPSPEC_DIR=$(APP_BSP_PRIVATEDIR)/chipspec
APP_BSP_ETC_SCRIPT=$(APP_BSP_PRIVATEDIR)/etc_script
APP_BSP_ETC_USR=$(APP_BSP_PRIVATEDIR)/etc_usr
APP_BSP_DEVGEN=$(APP_BSP_PRIVATEDIR)/devgen
APP_BSP_ECNT_MMC_DIR=$(APP_BSP_PRIVATEDIR)/ecnt_mmc
APP_BSP_WIFI_TRAFFIC_MGR_DIR=$(APP_BSP_PRIVATEDIR)/wifi_traffic_mgr

#APP_BSP_API_ATM_LIB_DIR=$(APP_BSP_API_DIR)/hw_driver/atm/lib_src
#APP_BSP_API_ATM_CMD_DIR=$(APP_BSP_API_DIR)/hw_driver/atm/cmd
#APP_BSP_API_PTM_LIB_DIR=$(APP_BSP_API_DIR)/hw_driver/ptm/lib_src
#APP_BSP_API_PTM_CMD_DIR=$(APP_BSP_API_DIR)/hw_driver/ptm/cmd
#APP_BSP_API_XDSL_LIB_DIR=$(APP_BSP_API_DIR)/hw_driver/xdsl/lib_src
#APP_BSP_API_XDSL_CMD_DIR=$(APP_BSP_API_DIR)/hw_driver/xdsl/cmd
#APP_BSP_API_DBG_LIB_DIR=$(APP_BSP_API_DIR)/ecnt_lib_dbg
#APP_BSP_API_ECNT_PRINTF_DIR=$(APP_BSP_API_DIR)/ecnt_lib_printf
#APP_BSP_API_UTL_LIB_DIR=$(APP_BSP_API_DIR)/ecnt_lib_utility
#APP_BSP_API_PORTBIND_LIB_DIR=$(APP_BSP_API_DIR)/ecnt_lib_portbind
APP_BSP_INIT_SCRIPT_DIR=$(APP_BSP_EXCLUSIVE_PRIVATE_DIR)/init_script
APP_BSP_IGMP_PROXY_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/igmpproxy-0.1
APP_BSP_MLD_PROXY_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/ecmh-2005.02.09
ifneq ($(strip $(TCSUPPORT_CF)),)
APP_BSP_EBTABLES_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/ebtables-2.0.11
else
APP_BSP_EBTABLES_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/ebtables-v2.0.8-2
endif
#APP_BSP_API_FE_LIBBSP_DIR=$(APP_BSP_API_DIR)/hw_driver/fe/libbsp_src
#APP_BSP_API_FE_CMD_DIR=$(APP_BSP_API_DIR)/hw_driver/fe/cmd
#APP_BSP_API_SWITCH_LIB_DIR=$(APP_BSP_API_DIR)/hw_driver/switch/lib_src
#APP_BSP_API_SWITCH_LIBBSP_DIR=$(APP_BSP_API_DIR)/hw_driver/switch/libbsp_src
#APP_BSP_API_SWITCH_CMD_DIR=$(APP_BSP_API_DIR)/hw_driver/switch/cmd
#APP_BSP_API_PPE_LIB_DIR=$(APP_BSP_API_DIR)/hw_driver/ppe/lib_src
#APP_BSP_API_PPE_LIBBSP_DIR=$(APP_BSP_API_DIR)/hw_driver/ppe/libbsp_src
#APP_BSP_API_PPE_CMD_DIR=$(APP_BSP_API_DIR)/hw_driver/ppe/cmd
#APP_BSP_API_NPU_CMD_DIR=$(APP_BSP_API_DIR)/hw_driver/npu/cmd
#APP_BSP_API_QDMA_LIB_DIR=$(APP_BSP_API_DIR)/hw_driver/qdma/lib_src
#APP_BSP_API_QDMA_LIBBSP_DIR=$(APP_BSP_API_DIR)/hw_driver/qdma/libbsp_src
#APP_BSP_API_QDMA_CMD_DIR=$(APP_BSP_API_DIR)/hw_driver/qdma/cmd
#APP_BSP_API_HW_NAT_CMD_DIR=$(APP_BSP_API_DIR)/hw_driver/hw_nat/cmd
#export APP_BSP_API_QDMA_LIB_DIR
#APP_BSP_API_QOS_LIB_DIR = $(APP_BSP_API_DIR)/hw_driver/qos/lib_src
#export APP_BSP_API_QOS_LIB_DIR
#APP_BSP_API_QOS_CMD_DIR = $(APP_BSP_API_DIR)/hw_driver/qos/cmd
#APP_BSP_API_CPUTEMP_LIB_DIR = $(APP_BSP_API_DIR)/hw_driver/cpu/lib_src
#export APP_BSP_API_CPUTEMP_LIB_DIR
#APP_BSP_API_CPUTEMP_CMD_DIR = $(APP_BSP_API_DIR)/hw_driver/cpu/cmd
#APP_BSP_API_WIFI_LIB_DIR=$(APP_BSP_API_DIR)/hw_driver/wifi/lib_src
#APP_BSP_API_WIFI_CMD_DIR=$(APP_BSP_API_DIR)/hw_driver/wifi/cmd
#APP_BSP_API_CPU_INTERRUPT_LIB_DIR=$(APP_BSP_API_DIR)/hw_driver/cpu_interrupt/lib_src
#APP_BSP_API_CPU_INTERRUPT_CMD_DIR=$(APP_BSP_API_DIR)/hw_driver/cpu_interrupt/cmd
#APP_BSP_API_ECNT_IGMP_LIB_DIR=$(APP_BSP_API_DIR)/hw_driver/ecnt_igmp/lib_src
#APP_BSP_API_ECNT_IGMP_CMD_DIR=$(APP_BSP_API_DIR)/hw_driver/ecnt_igmp/cmd

#APP_BSP_API_QOSRULE_LIB_DIR=$(APP_BSP_API_DIR)/hw_driver/qosrule/lib_src
#export APP_BSP_API_QOSRULE_LIB_DIR
#APP_BSP_API_IFC_LIB_DIR=$(APP_BSP_API_DIR)/hw_driver/ifc/lib_src
#export APP_BSP_API_IFC_LIB_DIR
#APP_BSP_API_IFC_CMD_DIR=$(APP_BSP_API_DIR)/hw_driver/ifc/cmd
#export APP_BSP_API_IFC_CMD_DIR

#APP_BSP_MESH_DIR=$(APP_BSP_API_DIR)/hw_driver/mesh
#export APP_BSP_MESH_DIR

APP_BSP_MTD_DIR=$(APP_BSP_EXCLUSIVE_PUBLIC_DIR)/mtd
export APP_BSP_MTD_DIR

APP_BSP_API_LIB_OUTPUT_DIR=$(APP_BSP_LIB_DIR)
export APP_BSP_API_LIB_OUTPUT_DIR

KERNEL_EXT_DIR=$(TRUNK_DIR)/kernel_ext

KERNEL_DIR=$(TRUNK_DIR)/linux

ifneq ($(strip $(TCSUPPORT_2_6_36_KERNEL)),)
CUSKIT_KERNEL_DIR=$(CUSKIT_DIR)/linux-2.6.36
KERNEL_DIR=$(TRUNK_DIR)/linux-2.6.36
KERNEL_USB_EXT_DIR=linux-2.6.36
endif
KERNEL_HEADER=$(KERNEL_DIR)/include
IPTABLE_KERNEL_DIR=$(KERNEL_DIR)

ifneq ($(strip $(TCSUPPORT_3_18_21_KERNEL)),)
CUSKIT_KERNEL_DIR=$(CUSKIT_DIR)/linux-3.18.21
KERNEL_DIR=$(TRUNK_DIR)/linux-3.18.21
KERNEL_HEADER=$(KERNEL_DIR)/usr/include
IPTABLE_KERNEL_DIR=$(KERNEL_DIR)/usr
KERNEL_USB_EXT_DIR=linux-3.18.21
endif

ifneq ($(strip $(TCSUPPORT_4_4_KERNEL)),)
CUSKIT_KERNEL_DIR=$(CUSKIT_DIR)/linux-4.4.115
KERNEL_DIR=$(TRUNK_DIR)/linux-4.4.115
KERNEL_HEADER=$(KERNEL_DIR)/usr/include
IPTABLE_KERNEL_DIR=$(KERNEL_DIR)/usr
KERNEL_USB_EXT_DIR=linux-4.4.115
endif

ifneq ($(strip $(TCSUPPORT_5_4_KERNEL)),)
CUSKIT_KERNEL_DIR=$(CUSKIT_DIR)/linux-5.4.55
KERNEL_DIR=$(TRUNK_DIR)/linux-5.4.55
KERNEL_HEADER=$(KERNEL_DIR)/usr/include
IPTABLE_KERNEL_DIR=$(KERNEL_DIR)/usr
KERNEL_USB_EXT_DIR=linux-5.4.55
endif

ifneq ($(strip $(TCSUPPORT_6_1_KERNEL)),)
CUSKIT_KERNEL_DIR=$(CUSKIT_DIR)/linux-6.1.47
KERNEL_DIR=$(TRUNK_DIR)/linux-6.1.47
KERNEL_HEADER=$(KERNEL_DIR)/usr/include
IPTABLE_KERNEL_DIR=$(KERNEL_DIR)/usr
KERNEL_USB_EXT_DIR=linux-6.1.47
endif

ifneq ($(strip $(TCSUPPORT_5_10_KERNEL)),)
CUSKIT_KERNEL_DIR=$(CUSKIT_DIR)/linux-5.10.146
KERNEL_DIR=$(TRUNK_DIR)/linux-5.10.146
KERNEL_HEADER=$(KERNEL_DIR)/usr/include
IPTABLE_KERNEL_DIR=$(KERNEL_DIR)/usr
KERNEL_USB_EXT_DIR=linux-5.10.146
endif

ifneq ($(strip $(TCSUPPORT_6_6_KERNEL)),)
CUSKIT_KERNEL_DIR=$(CUSKIT_DIR)/linux-6.6.23
KERNEL_DIR=$(TRUNK_DIR)/linux-6.6.23
KERNEL_HEADER=$(KERNEL_DIR)/usr/include
IPTABLE_KERNEL_DIR=$(KERNEL_DIR)/usr
KERNEL_USB_EXT_DIR=linux-6.6.23
endif

export CUSKIT_KERNEL_DIR
export KERNEL_DIR
export KERNEL_HEADER
export KERNEL_USB_EXT_DIR

export KERNEL_ECNT_DIR
export KERNEL_ECNT_INC_DIR=$(KERNEL_ECNT_DIR)/include
KERNEL_EXT_DIR=$(KERNEL_ECNT_DIR)
export KERNEL_EXT_DIR

KERNEL_EXT_INC_DIR=$(KERNEL_ECNT_DIR)/include
export KERNEL_EXT_INC_DIR
KERNEL_EXT_SPI_NAND_DIR=$(KERNEL_ECNT_DIR)/drivers/mtd/chips
export KERNEL_EXT_SPI_NAND_DIR
KERNEL_EXT_LIB_DIR=$(KERNEL_ECNT_DIR)/lib
export KERNEL_EXT_LIB_DIR
KERNEL_ECNT_ARCH_ARM_ECNT_DIR=$(KERNEL_ECNT_DIR)/arch/arm/mach-econet
export KERNEL_ECNT_ARCH_ARM_ECNT_DIR
KERNEL_ECNT_ARCH_ARM_INC_DIR=$(KERNEL_ECNT_DIR)/arch/arm/include
export KERNEL_ECNT_ARCH_ARM_INC_DIR

export KERNEL_ARHT_DIR=$(TRUNK_DIR)/linux-arht
export KERNEL_ARHT_GENERIC_DIR=$(TRUNK_DIR)/linux-6/generic-6.6
export GLOBAL_INC_DIR=$(TRUNK_DIR)/global_inc
export GLOBAL_FLASH_LAYOUT_INC_DIR=$(GLOBAL_INC_DIR)/flash_layout

MODULE_DIR=$(TRUNK_DIR)/modules
MODULES_PRIV_SRC_DIR=$(MODULE_DIR)/private
MODULES_PUBLIC_SRC_DIR=$(MODULE_DIR)/public
export TOOLS_DIR=$(TRUNK_DIR)/tools
TOOLS_TRX_DIR=$(TOOLS_DIR)/trx
export TOOLS_TRX_DIR
TOOLS_UBOOT_DIR=$(TOOLS_DIR)/uboot
export TOOLS_UBOOT_DIR
ECNT_VERSION_DIR=$(GLOBAL_INC_DIR)/version
export ECNT_VERSION_DIR

MODULES_SOC_BSP_DIR=$(TRUNK_DIR)/BSP/soc_bsp/modules
MODULES_SOC_BSP_EXT_DIR=$(TRUNK_DIR)/../critical_ip/tclinux_phoenix/BSP/soc_bsp
MODULES_SOC_BSP_MOD_EXT_DIR=$(MODULES_SOC_BSP_EXT_DIR)/modules

#ifneq ($(strip $(CUSTOMER_BUILD_RELEASECODE)),)
#DMT_DIR=$(MODULE_DIR)/dmt
#else
DMT_DIR=$(MODULES_PRIV_SRC_DIR)/dmt
#endif
#ifneq ($(strip $(CUSTOMER_BUILD_RELEASECODE)),)
#MODULES_BACKUP=$(MODULES_PRIV_SRC_DIR)/ko/modules
#else
MODULES_BACKUP=$(MODULES_PRIV_SRC_DIR)/ko/modules
#endif
MODULES_IGMPSNOOP_DIR=$(MODULES_PRIV_SRC_DIR)/net/igmpsnooping
MODULES_ACCESSLIMIT_DIR=$(MODULES_PRIV_SRC_DIR)/net/access_limit
MODULES_SWQOS_DIR=$(MODULES_PRIV_SRC_DIR)/net/qos_discipline
MODULES_SOFT_RATELIMIT_DIR=$(MODULES_PRIV_SRC_DIR)/net/soft_ratelimit
MODULES_URL_FILTER_DIR=$(MODULES_PRIV_SRC_DIR)/net/url_filter
MODULES_LOOP_DETECT_DIR=$(MODULES_PRIV_SRC_DIR)/net/loop_detect
MODULES_MAXNET_DPI_DIR=$(MODULES_PRIV_SRC_DIR)/net/maxnetdpi
MODULES_PLUGIN_NETLIMIT_DIR=$(MODULES_PRIV_SRC_DIR)/net/plugin_netlimit
MODULES_INFO_UTILITY_DIR=$(MODULES_PRIV_SRC_DIR)/net/info_utility
MODULES_TRAFFIC_PROCESS_DIR=$(MODULES_PRIV_SRC_DIR)/net/trafficprocess
MODULES_NP_LANHOST_MGR_DIR=$(MODULES_PRIV_SRC_DIR)/net/np_lanhost_mgr
MODULES_ATTACK_PROTECT_DIR=$(MODULES_PRIV_SRC_DIR)/net/attackprotector
MODULES_NP_LANHOST_MGR_DIR=$(MODULES_PRIV_SRC_DIR)/net/np_lanhost_mgr
MODULES_ETHERTYPE_FILTER_DIR=$(MODULES_PRIV_SRC_DIR)/net/ethertype_filter
MODULES_DATASPEED_LIMIT_DIR=$(MODULES_PRIV_SRC_DIR)/net/dataspeed_limit
MODULES_BRIDGE_DETECT_DIR=$(MODULES_PRIV_SRC_DIR)/net/bridge_detect
MODULES_APP_ROUTE_MGR_DIR=$(MODULES_PRIV_SRC_DIR)/net/app_route_mgr
MODULES_APP_FILTER_MGR_DIR=$(MODULES_PRIV_SRC_DIR)/net/app_filter_mgr
MODULES_ECNT_HOOK_DIR=$(MODULES_PRIV_SRC_DIR)/kernel_hook
MODULES_SIMCARD_DIR=$(MODULES_PRIV_SRC_DIR)/simcard_separation
ifneq ($(strip $(TCSUPPORT_SIMCARD_GENERAL)),)
MODULES_SIMCARD_DIR=$(MODULES_PRIV_SRC_DIR)/simcard_separation_general
endif
MODULES_TC3262_DIR=$(MODULES_PRIV_SRC_DIR)/tc3262
MODULES_MT7510_PTM_DIR=$(MODULES_PRIV_SRC_DIR)/mt7510_ptm
MODULES_BONDING_PCIE_DIR=$(MODULES_PRIV_SRC_DIR)/bonding_pcie
MODULES_RAETH_DIR=$(MODULES_PRIV_SRC_DIR)/raeth
MODULES_ETHER_DIR=$(MODULES_PRIV_SRC_DIR)/ether/en7512
MODULES_ETHER_8851_DIR=$(MODULES_PRIV_SRC_DIR)/ether/en8851
MODULES_ETHER_UPSTREAM_DIR=$(MODULES_PRIV_SRC_DIR)/upstream/ether
export MODULES_ETHER_UPSTREAM_DIR
MODULES_FHT_VLAN_DIR=$(MODULES_PRIV_SRC_DIR)/fh_vlan/en7512
MODULES_FHT_VLAN_FILTER_DIR=$(MODULES_PRIV_SRC_DIR)/fh_vlan/en7523
ifneq ($(strip $(TCSUPPORT_CPU_AN7583)),)
MODULES_ETHER_PHY_DIR=$(MODULES_ENB_BSP_DIR)/tcphy
else
MODULES_ETHER_PHY_DIR=$(MODULES_PRIV_SRC_DIR)/tcphy
endif
MODULES_THERMAL_DIR=$(MODULES_PRIV_SRC_DIR)/thermal
MODULES_PWR_SENSOR_DIR=$(TRUNK_DIR)/BSP/current_sensor
MODULES_DIAG_DIR=$(MODULES_PRIV_SRC_DIR)/diag_tools
ifneq ($(strip $(TCSUPPORT_XSI_ENABLE)),)
MODULES_XSI_MAC_DIR=$(MODULES_PRIV_SRC_DIR)/xsi/xsi_mac
MODULES_XSI_WAN_MAC_DIR=$(MODULES_PRIV_SRC_DIR)/xsi/xsi_wan_mac
MODULES_XSI_PHY_DIR=$(MODULES_PRIV_SRC_DIR)/xsi/xsi_phy
export MODULES_XSI_PHY_DIR
endif
MODULES_AE_WAN_MAC_DIR=$(MODULES_PRIV_SRC_DIR)/xsi/ae_wan_mac
MODULES_HSGMII_LAN_MAC_DIR=$(MODULES_PRIV_SRC_DIR)/xsi/hsgmii_lan_mac
MODULES_HSGMII_LAN_MAC_7581_DIR=$(MODULES_PRIV_SRC_DIR)/xsi/hsgmii_lan_mac_7581
MODULES_DIAG_TOOL=$(MODULES_PRIV_SRC_DIR)/diag_tools
export MODULES_RAETH_DIR

MODULES_CRITICAL_DP_DIR=$(TRUNK_DIR)/BSP/critical_ip_bsp/dp_bsp

MODULES_CRITICAL_DP_RA_HWNAT_V3_DIR=$(MODULES_CRITICAL_DP_DIR)/ra_hwnat_v3
export MODULES_CRITICAL_DP_RA_HWNAT_V3_DIR

MODULES_CRITICAL_DP_IFC_DIR=$(MODULES_CRITICAL_DP_DIR)/ifc
export MODULES_CRITICAL_DP_IFC_DIR
MODULES_CRITICAL_DP_SPEEDTEST_DIR=$(MODULES_CRITICAL_DP_DIR)/speedtest
MODULES_CRITICAL_DP_TR471_SPEEDTEST_DIR=$(MODULES_CRITICAL_DP_DIR)/tr471_speedtest
MODULES_UNOPEN_DP_DIR=$(TRUNK_DIR)/BSP/unopen_ip/dp
MODULES_UNOPEN_DP_DIAG_TOOLS_DIR=$(MODULES_UNOPEN_DP_DIR)/diag_tools
MODULES_UNOPEN_DP_GRE_HW_OFFLOAD_DIR=$(MODULES_UNOPEN_DP_DIR)/tunnel_offload/gre_hw_offload
MODULES_UNOPEN_DP_L2TP_OFFLOAD_DIR=$(MODULES_UNOPEN_DP_DIR)/tunnel_offload/l2tp_offload
MODULES_UNOPEN_DP_PPTP_OFFLOAD_DIR=$(MODULES_UNOPEN_DP_DIR)/tunnel_offload/pptp_offload
MODULES_UNOPEN_DP_VXLAN_HW_OFFLOAD_DIR=$(MODULES_UNOPEN_DP_DIR)/tunnel_offload/vxlan_hw_offload
MODULES_UNOPEN_DP_SW_NAT_DIR=$(MODULES_UNOPEN_DP_DIR)/sw_nat
MODULES_UNOPEN_DP_SOFT_RATELIMIT_DIR=$(MODULES_UNOPEN_DP_DIR)/soft_ratelimit
MODULES_UNOPEN_DP_ETHER_SOFT_QDMA_DIR=$(MODULES_UNOPEN_DP_DIR)/soft_dma/ether
MODULES_UNOPEN_DP_SOFT_DMA_EN7512_DIR=$(MODULES_UNOPEN_DP_DIR)/soft_dma/qdma/EN7512
MODULES_UNOPEN_DP_SOFT_DMA_EN7516_DIR=$(MODULES_UNOPEN_DP_DIR)/soft_dma/qdma/EN7516
APPS_UNOPEN_DP_IGMPV3PROXY_DIR=$(MODULES_UNOPEN_DP_DIR)/igmpv3proxy

MODULES_CRITICAL_DP_EXT_DIR=$(TRUNK_DIR)/../critical_ip/tclinux_phoenix/BSP/critical_ip_bsp/dp_bsp
MODULES_CRITICAL_DP_SPEEDTEST_EXT_DIR=$(MODULES_CRITICAL_DP_EXT_DIR)/speedtest
MODULES_CRITICAL_DP_RA_HWNAT_V3_EXT_DIR=$(MODULES_CRITICAL_DP_EXT_DIR)/ra_hwnat_v3
MODULES_CRITICAL_DP_IFC_EXT_DIR=$(MODULES_CRITICAL_DP_EXT_DIR)/ifc
MODULES_CRITICAL_DP_TR471_SPEEDTEST_EXT_DIR=$(MODULES_CRITICAL_DP_EXT_DIR)/tr471_speedtest
MODULES_UNOPEN_DP_EXT_DIR=$(TRUNK_DIR)/../critical_ip/tclinux_phoenix/BSP/dp_bsp
MODULES_UNOPEN_DP_DIAG_TOOLS_EXT_DIR=$(MODULES_UNOPEN_DP_EXT_DIR)/diag_tools
MODULES_UNOPEN_DP_GRE_HW_OFFLOAD_EXT_DIR=$(MODULES_UNOPEN_DP_EXT_DIR)/tunnel_offload/gre_hw_offload
MODULES_UNOPEN_DP_L2TP_OFFLOAD_EXT_DIR=$(MODULES_UNOPEN_DP_EXT_DIR)/tunnel_offload/l2tp_offload
MODULES_UNOPEN_DP_VXLAN_HW_OFFLOAD_EXT_DIR=$(MODULES_UNOPEN_DP_EXT_DIR)/tunnel_offload/vxlan_hw_offload
MODULES_UNOPEN_DP_SW_NAT_EXT_DIR=$(MODULES_UNOPEN_DP_EXT_DIR)/sw_nat
MODULES_UNOPEN_DP_SOFT_RATELIMIT_EXT_DIR=$(MODULES_UNOPEN_DP_EXT_DIR)/soft_ratelimit
MODULES_UNOPEN_DP_ETHER_SOFT_QDMA_EXT_DIR=$(MODULES_UNOPEN_DP_EXT_DIR)/soft_dma/ether
MODULES_UNOPEN_DP_SOFT_DMA_EN7512_EXT_DIR=$(MODULES_UNOPEN_DP_EXT_DIR)/soft_dma/qdma/EN7512
MODULES_UNOPEN_DP_SOFT_DMA_EN7516_EXT_DIR=$(MODULES_UNOPEN_DP_EXT_DIR)/soft_dma/qdma/EN7516
APPS_UNOPEN_DP_IGMPV3PROXY_EXT_DIR=$(MODULES_UNOPEN_DP_EXT_DIR)/igmpv3proxy

MODULES_HWNAT_DIR=$(MODULES_PRIV_SRC_DIR)/hwnat
MODULES_RA_HWNAT_DIR=$(MODULES_PRIV_SRC_DIR)/ra_hwnat
MODULES_RA_HWNAT_7510_DIR=$(MODULES_PRIV_SRC_DIR)/ra_hwnat_7510
export MODULES_RA_HWNAT_7510_DIR
MODULES_RA_HWNAT_V3_DIR=$(MODULES_PRIV_SRC_DIR)/ra_hwnat_v3
export MODULES_RA_HWNAT_V3_DIR

MODULES_FE_PPE_TEST_DIR=$(MODULES_PRIV_SRC_DIR)/fe_ppe_test
MODULES_KPROFILE_DIR=$(MODULES_PRIV_SRC_DIR)/kprofile
WIFI_DRIVER_BASE=$(MODULES_PRIV_SRC_DIR)/wifi
RT2561AP_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/rt61ap/Module
RT3390AP_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/2009_1106_RT3390_LinuxAP_V2.3.2.0_DPA
RT5392AP_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/RT5392_Linux_AP_V2.5.0.0_DPA
RT5592AP_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/RT5592_LinuxAP_20111128_V2.6.0.0_DPA
RT3593AP_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/RT3593_LinuxAP_V2.6.0.0_DPA
MT7601EAP_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7601E_LinuxAP_20130305_DPA
ifneq ($(strip $(TCSUPPORT_WLAN_MT7592_V41)),)
MT7592AP_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7603_V4.1
else
ifneq ($(strip $(TCSUPPORT_WLAN_MT7592_V4123)),)
MT7592AP_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7603_V4.1.2.3
else
MT7592AP_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7603
endif
endif
WIFI_MULTI_DRIVER_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/DPA_RT5592_RT5392_LinuxAP_V2.7.x.x
#RT3090AP_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/2009_0209_RT3090_LinuxAP_V2.1.3.0
MT7610EAP_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/mt7610e_wifi_v3009_dpa_20150430
MT7612EAP_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7612E_LinuxAP_3.0.4.0.P2_DPA
ifneq ($(strip $(TCSUPPORT_WLAN_MT7613_V60)),)
MT7613EAP_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7613/V6.0.2.0
else
ifneq ($(strip $(TCSUPPORT_WLAN_MT7613_V6040)),)
MT7613EAP_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7613/V6.0.4.0
else
MT7613EAP_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7613/V4.4.0.2
endif
endif
MT7615EAP_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7615
MT7615OFFLOAD_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7615_offload/V5.0.2.0
ifneq ($(strip $(TCSUPPORT_WLAN_MT7915_V73)),)
MT7915EAP_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7915_v7.3
ifneq ($(strip $(TCSUPPORT_WLAN_MT7915_BUILD_IN)),)
RT28xx_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7915_v7.3
RT28xx_BIN_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7915_v7.3
endif
else
MT7915EAP_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7915
ifneq ($(strip $(TCSUPPORT_WLAN_MT7915_BUILD_IN)),)
RT28xx_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7915
RT28xx_BIN_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7915
endif
endif
ifneq ($(strip $(TCSUPPORT_WLAN_MT7915_V74)),)
MT7915EAP_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7915_v7.4
ifneq ($(strip $(TCSUPPORT_WLAN_MT7915_BUILD_IN)),)
RT28xx_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7915_v7.4
RT28xx_BIN_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7915_v7.4
endif
endif
ifneq ($(strip $(TCSUPPORT_WLAN_MT7993)),)
export WIFI_DRIVER_VERSION=MT7993
MODULES_WIRELESSREGDBSUBDIRS=$(WIFI_DRIVER_BASE)/$(WIFI_DRIVER_VERSION)/wireless-regdb-2021.04.21
MODULES_WIFI_CMN_DRIVER=$(WIFI_DRIVER_BASE)/$(WIFI_DRIVER_VERSION)/mt_wifi_cmn
export MODULES_WIFI_OSAL_DRIVER=$(WIFI_DRIVER_BASE)/$(WIFI_DRIVER_VERSION)/wifi_osal
export MODULES_WIFI_GRIFFIN_DRIVER=$(WIFI_DRIVER_BASE)/$(WIFI_DRIVER_VERSION)/mt_wifi7
export MODULES_WIFI_GRIFFIN_HWIFI_DRIVER=$(MODULES_WIFI_GRIFFIN_DRIVER)/wlan_hwifi
export MODULES_WIFI_GRIFFIN_AP_DRIVER=$(MODULES_WIFI_GRIFFIN_DRIVER)/mt_wifi_ap
export MODULES_WIFI_80211_DRIVER=$(WIFI_DRIVER_BASE)/$(WIFI_DRIVER_VERSION)/mac80211
export MODULES_WIFI_80211_BACKPORT_DRIVER=$(MODULES_WIFI_80211_DRIVER)/backports-6.5
export MODULES_WIFI_80211_DRIVER_INC=$(MODULES_WIFI_80211_DRIVER)/include
export MODULES_WIFI_OSAL_DRIVER_INC=$(MODULES_WIFI_OSAL_DRIVER)/inc
export MODULES_WIFI_QOS_DRIVER=$(WIFI_DRIVER_BASE)/$(WIFI_DRIVER_VERSION)/mtqos
endif
ifneq ($(strip $(TCSUPPORT_WLAN_MT7916D)),)
MT7916EAP_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7916
ifneq ($(strip $(TCSUPPORT_WLAN_MT7916_BUILD_IN)),)
RT28xx_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7916
RT28xx_BIN_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7916
endif
endif
ifneq ($(strip $(TCSUPPORT_WLAN_MT7916_V7623)),)
MT7916EAP_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7916_v7623
ifneq ($(strip $(TCSUPPORT_WLAN_MT7916_BUILD_IN)),)
RT28xx_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7916_v7623
RT28xx_BIN_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7916_v7623
endif
endif
ifneq ($(strip $(TCSUPPORT_WLAN_MT7615_V33)),)
ifeq ($(strip $(TCSUPPORT_WLAN_MT7615_BUILD_IN)),)
MT7615V3X_DIR_SRC=$(MODULES_PRIV_SRC_DIR)/wifi/MT7615_V3.3
MT7615V3X_DIR_DST=$(TRUNK_DIR)/MT7615_V3.3
endif
ifeq ($(strip $(TCSUPPORT_WLAN_MT7615_BUILD_IN)),)
#MT7615V3X_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7615_V3.3/V5.0.3.0
#MT7615V3X_CFG_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7615_V3.3/wlan_cfg
#MT7615V3X_BIN_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7615_V3.3/bin
MT7615V3X_DIR=$(TRUNK_DIR)/MT7615_V3.3/V5.0.3.0
MT7615V3X_CFG_DIR=$(TRUNK_DIR)/MT7615_V3.3/wlan_cfg
MT7615V3X_BIN_DIR=$(TRUNK_DIR)/MT7615_V3.3/bin
else
MT7615V3X_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7615_V3.3/V5.0.3.0
MT7615V3X_CFG_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7615_V3.3/wlan_cfg
MT7615V3X_BIN_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7615_V3.3/bin
endif
endif
ifneq ($(strip $(TCSUPPORT_WLAN_MT7615_V34)),)
ifeq ($(strip $(TCSUPPORT_WLAN_MT7615_BUILD_IN)),)
MT7615V3X_DIR_SRC=$(MODULES_PRIV_SRC_DIR)/wifi/MT7615_V3.4
MT7615V3X_DIR_DST=$(TRUNK_DIR)/MT7615_V3.4
endif
ifeq ($(strip $(TCSUPPORT_WLAN_MT7615_BUILD_IN)),)
#MT7615V3X_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7615_V3.4/V5.0.4.0
#MT7615V3X_CFG_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7615_V3.4/wlan_cfg
#MT7615V3X_BIN_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7615_V3.4/bin
ifeq ($(strip $(TCSUPPORT_WLAN_MULTI_CHIP)),)
MT7615V3X_DIR=$(TRUNK_DIR)/wifi/MT7615_V3.4/V5.0.4.0
MT7615V3X_CFG_DIR=$(TRUNK_DIR)/wifi/MT7615_V3.4/wlan_cfg
MT7615V3X_BIN_DIR=$(TRUNK_DIR)/wifi/MT7615_V3.4/bin
else
MT7615V3X_DIR=$(TRUNK_DIR)/MT7615_V3.4/V5.0.4.0
MT7615V3X_CFG_DIR=$(TRUNK_DIR)/MT7615_V3.4/wlan_cfg
MT7615V3X_BIN_DIR=$(TRUNK_DIR)/MT7615_V3.4/bin
endif
else
MT7615V3X_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7615_V3.4/V5.0.4.0
MT7615V3X_CFG_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7615_V3.4/wlan_cfg
MT7615V3X_BIN_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/MT7615_V3.4/bin
endif
endif
RT3090AP_DIR=$(MODULES_PRIV_SRC_DIR)/wifi/2009_0904_RT3090_LinuxAP_v2.3.0.0_TC_for_3092
MODULES_FTTDP_INIC_DIR=$(MODULES_PRIV_SRC_DIR)/fttdp_inic
MODULES_FULLCONE_DIR=$(MODULES_PRIV_SRC_DIR)/net/full_cone
MODULES_MULTIWAN_DIR=$(MODULES_PRIV_SRC_DIR)/net/multi_wan
MODULES_PORTBIND_DIR=$(MODULES_PRIV_SRC_DIR)/net/portbind
MODULES_SWNAT_DIR=$(MODULES_PRIV_SRC_DIR)/net/sw_nat
MODULES_VLAN_TAG_DIR=$(MODULES_PRIV_SRC_DIR)/net/vlan_tag
MODULES_CT_VLAN_TAG_DIR=$(MODULES_PRIV_SRC_DIR)/net/vlan_tag_ct
MODULES_AUTOBENCH_DIR=$(MODULES_PRIV_SRC_DIR)/auto_bench
ifeq ($(strip $(TCSUPPORT_CPU_ARMV8)),)
MODULES_DYING_GASP_DIR=$(MODULES_PRIV_SRC_DIR)/net/dying_gasp
else
MODULES_DYING_GASP_DIR=$(MODULES_PRIV_SRC_DIR)/dying_gasp
endif
MODULES_PWM_DIR=$(MODULES_PRIV_SRC_DIR)/net/pwm
MODULES_FE_7512_DIR=$(MODULES_PRIV_SRC_DIR)/fe/en7512
MODULES_TSO_DIR=$(MODULES_PRIV_SRC_DIR)/tso
MODULES_TSO_VERIFY_DIR=$(MODULES_PRIV_SRC_DIR)/tso/verify
MODULES_LRO_DIR=$(MODULES_PRIV_SRC_DIR)/lro
MODULES_LRO_VERIFY_DIR=$(MODULES_PRIV_SRC_DIR)/lro/verify
MODULES_NTFS3_DIR=$(MODULES_PRIV_SRC_DIR)/ntfs3
export MODULES_FE_7512_DIR
MODULES_QDMA_EN_DIR=$(MODULES_PRIV_SRC_DIR)/qdma
export MODULES_QDMA_EN_DIR
MODULES_QDMA_7516_DIR=$(MODULES_PRIV_SRC_DIR)/qdma/EN7516
MODULES_QDMA_7516_UPSTREAM_DIR=$(MODULES_PRIV_SRC_DIR)/upstream/qdma
export MODULES_QDMA_7516_DIR
export MODULES_QDMA_7516_UPSTREAM_DIR
MODULES_QDMA_7512_DIR=$(MODULES_PRIV_SRC_DIR)/qdma/EN7512
export MODULES_QDMA_7512_DIR
MODULES_QDMA_DIR=$(MODULES_PRIV_SRC_DIR)/bufmgr
export MODULES_QDMA_DIR
MODULES_SLM_DIR=$(MODULES_PRIV_SRC_DIR)/slm_verify
export MODULES_SLM_DIR
MODULES_IFC_DIR=$(MODULES_PRIV_SRC_DIR)/IFC
export MODULES_IFC_DIR
MODULES_LDDLA_1G_DIR =$(MODULES_PRIV_SRC_DIR)/lddla_1g
export MODULES_LDDLA_1G_DIR
MODULES_PHY_DIR=$(MODULES_PRIV_SRC_DIR)/xpon_phy
export MODULES_PHY_DIR
MODULES_PHY_10G_DIR=$(MODULES_PRIV_SRC_DIR)/xpon_phy_10g
export MODULES_PHY_10G_DIR
MODULES_TOD_GEN_DIR=$(MODULES_PRIV_SRC_DIR)/tod_gen
export MODULES_TOD_GEN_DIR
MODULES_AN8901_DIR=$(MODULES_PRIV_SRC_DIR)/an8901
export MODULES_AN8901_DIR
MODULES_LDDLA_DIR=$(MODULES_PRIV_SRC_DIR)/lddla
export MODULES_LDDLA_DIR
MODULES_VDSL_WAN_DIR=$(MODULES_PRIV_SRC_DIR)/mt7510_ptm
export MODULES_VDSL_WAN_DIR
FILESYSTEM_DIR=$(BSP_EXT_FS)
export FILESYSTEM_DIR
FILESYSTEM_BSP_DIR=$(TRUNK_DIR)/filesystem
export FILESYSTEM_BSP_DIR
FILESYSTEM_ORI_DIR=$(TRUNK_DIR)/filesystem_original
export FILESYSTEM_ORI_DIR

export PON_PHY_DIR=$(TRUNK_DIR)/BSP/phy/pon_phy
export IS_PON_PHY_DIR_EXIST=$(if $(wildcard $(PON_PHY_DIR)/.),Y,N)

MODULES_USB_CAMERA_DRIVER=$(MODULES_PUBLIC_SRC_DIR)/usb_camera

LZMA_LIB=$(TOOLS_DIR)/squashfs-tools/lzma/C/7zip/Compress/LZMA_Lib
LZMA_ALONE=$(TOOLS_DIR)/squashfs-tools/lzma/C/7zip/Compress/LZMA_Alone
SPI_NAND_ECC_GEN=$(TOOLS_DIR)/spi_nand_ctrl_ecc
ifneq ($(strip $(TCSUPPORT_OPENWRT)),)
MBEDTLS=$(PKG_BUILD_DIR)/tools/mbedtls-2.5.1
else
MBEDTLS=$(TOOLS_DIR)/mbedtls-2.5.1
endif
export MBEDTLS
MODULES_FASTBRIDGE_DIR=$(MODULES_PRIV_SRC_DIR)/net/fastbridge

export DTC_DIR=$(TOOLS_DIR)/dtc-1.4.0

MODULES_INSTALL_PRIV_DIR=modules/private/ko/modules/$(TCPLATFORM)/
export MODULES_INSTALL_PRIV_DIR

MODULES_CRYPTO_DRIVER=$(MODULES_SOC_BSP_DIR)/cryptoDriver
MODULES_EIP93_DRIVERS=$(MODULES_PRIV_SRC_DIR)/eip93_drivers

INIC_CLIENT_FILE_DIR=$(FILESYSTEM_DIR)/userfs/VDSL_CO_file
INIC_CLIENT_FILE_BACKUP_DIR=$(TRUNK_DIR)/FTTdp_VDSL_CO_file

MODULES_ETHER_DOWNVLAN_DIR=$(MODULES_PRIV_SRC_DIR)/net/ether_downvlan

MODULES_ENB_BSP_DIR=$(TRUNK_DIR)/BSP/enb_bsp
MODULES_ENB_BSP_SGMII_DIR=$(MODULES_ENB_BSP_DIR)/sgmii
export MODULES_ENB_BSP_SGMII_DIR

ifneq ($(strip $(TCSUPPORT_ETHER_8811)),)
MODULES_ENB_BSP_PHY_AN8811_DIR=$(MODULES_ENB_BSP_DIR)/phy_an8811
MODULES_XSI_AN8811_BBU_API_DIR=$(MODULES_PRIV_SRC_DIR)/xsi/an8811/bbu_api
MODULES_XSI_AN8811_BBU_API_MDIO_ARHT_DIR=$(MODULES_PRIV_SRC_DIR)/xsi/an8811/bbu_api/mdio_arht
export MODULES_XSI_AN8811_BBU_API_DIR
export MODULES_XSI_AN8811_BBU_API_MDIO_ARHT_DIR
export MODULES_ENB_BSP_PHY_AN8811_DIR
endif

ifneq ($(strip $(TCSUPPORT_ETHER_8831)),)
MODULES_8831_DIR=$(TRUNK_DIR)/BSP/enb_bsp/phy_an8831/10Gphy/as21xx
MODULES_8831_BBU_API_DIR=$(TRUNK_DIR)/BSP/enb_bsp/phy_an8831/10Gphy/as21xx_bbu_api
MODULES_8831_BBU_API_MDIO_ARHT_DIR=$(TRUNK_DIR)/BSP/enb_bsp/phy_an8831/10Gphy/as21xx_bbu_api/mdio_arht
8831_UBOOT_DRIVER_DIR=$(TRUNK_DIR)/BSP/enb_bsp/phy_an8831/10Gphy/as21xx_uboot_driver
export MODULES_8831_DIR
export MODULES_8831_BBU_API_DIR
export MODULES_8831_BBU_API_MDIO_ARHT_DIR
export 8831_UBOOT_DRIVER_DIR
endif

#ifneq ($(strip $(TCSUPPORT_ECNT_MAP)),)
#delete fh bsp mesh
#ifneq ($(strip $(TCSUPPORT_ECNT_MAP_ENHANCE)),)
#APP_BSP_MAP_DIR=$(APP_BSP_EXCLUSIVE_PRIVATE_DIR)/map_enhance
#else
#APP_BSP_MAP_DIR=$(APP_BSP_EXCLUSIVE_PRIVATE_DIR)/map
#endif
#APP_BSP_MAP_WAPPD_DIR=$(APP_BSP_MAP_DIR)/wappd
#APP_BSP_MAP_1905DAEMON_DIR=$(APP_BSP_MAP_DIR)/1905daemon
#APP_BSP_MAP_LIBMAPD_DIR=$(APP_BSP_MAP_DIR)/libmapd
#APP_BSP_MAP_HAL_MAP_DIR=$(APP_BSP_MAP_DIR)/hal_map
#APP_BSP_MAP_MAPD_DIR=$(APP_BSP_MAP_DIR)/mapd
#export APP_BSP_MAP_DIR 
#export APP_BSP_MAP_WAPPD_DIR
#export APP_BSP_MAP_1905DAEMON_DIR
#export APP_BSP_MAP_LIBMAPD_DIR
#export APP_BSP_MAP_HAL_MAP_DIR
#export APP_BSP_MAP_MAPD_DIR
#endif

ifneq ($(strip $(TCSUPPORT_NP_CTC)),)
APP_ZLIB_DIR=$(APP_OPENSOURCE_DIR)/zlib-1.2.8
endif

#add bsp wapp
ifneq ($(strip $(TCSUPPORT_ECNT_MAP)),)
ifneq ($(strip $(TCSUPPORT_ECNT_MAP_ENHANCE)),)
export BSP_API_MAP_WAPPD_DIR=$(BSP_PRIVATEDIR)/wappd
endif
ifneq ($(strip $(TCSUPPORT_EASYMESH_R13)),)
export BSP_API_MAP_WAPPD_DIR=$(BSP_PRIVATEDIR)/wappd_v2
endif
ifneq ($(strip $(TCSUPPORT_MAP_R2)),)
export BSP_API_MAP_WAPPD_DIR=$(BSP_PRIVATEDIR)/wappd_r2
ifneq ($(strip $(TCSUPPORT_CF)),)
export BSP_MAP_ENDIR=$(BSP_PRIVATEDIR)/map_r2
endif
endif
endif

ifneq ($(strip $(TCSUPPORT_ECNT_MAP)),)
ifneq ($(strip $(TCSUPPORT_ECNT_MAP_ENHANCE)),)
#add bsp mesh_test
APP_BSP_MAP_DIR=$(APP_BSP_EXCLUSIVE_PRIVATE_DIR)/map_test
APP_BSP_MAP_1905DAEMON_DIR=$(APP_BSP_MAP_DIR)/1905daemon
APP_BSP_MAP_LIBMAPD_DIR=$(APP_BSP_MAP_DIR)/libmapd
APP_BSP_MAP_HAL_MAP_DIR=$(APP_BSP_MAP_DIR)/hal_map
APP_BSP_MAP_MAPD_DIR=$(APP_BSP_MAP_DIR)/mapd
export APP_BSP_MAP_DIR 
export APP_BSP_MAP_1905DAEMON_DIR
export APP_BSP_MAP_LIBMAPD_DIR
export APP_BSP_MAP_HAL_MAP_DIR
export APP_BSP_MAP_MAPD_DIR
endif
endif

ifneq ($(strip $(TCSUPPORT_EASYMESH_R13)),)
MODULE_MAP_FILTER_DIR=$(MODULES_PRIV_SRC_DIR)/mapfilter_v2
else
ifneq ($(strip $(TCSUPPORT_MAP_R2)),)
MODULE_MAP_FILTER_DIR=$(MODULES_PRIV_SRC_DIR)/mapfilter_r2
else
ifneq ($(strip $(TCSUPPORT_WIFI7_MAP_R6)),)
MODULE_MAP_FILTER_DIR=$(MODULES_PRIV_SRC_DIR)/mapfilter_r6
else
MODULE_MAP_FILTER_DIR=$(MODULES_PRIV_SRC_DIR)/mapfilter
endif
endif
endif

#ABDT
ifneq ($(strip $(TCSUPPORT_WLAN_AUTO_DEBUG_TOOL)),)
APP_WADT_DIR=$(APP_PRIVATE_DIR)/wadt
endif

#new bdp dir
export BSP_ROOTDIR=$(TRUNK_DIR)/app_bsp
export BSP_PRIVATEDIR=$(BSP_ROOTDIR)/private
export BSP_API_DIR=$(BSP_PRIVATEDIR)/API
export BSP_BLAPI_DIR=$(BSP_API_DIR)/ecnt_blapi

ifneq ($(strip $(TCSUPPORT_OPENWRT)),)
export BSP_INT_INSTALL=$(KERNEL_BUILD_DIR)/install_bsp_exclusive
else
export BSP_INT_INSTALL=$(BSP_ROOTDIR)/install_bsp_exclusive
endif
export BSP_INT_INC=$(BSP_INT_INSTALL)/inc
export BSP_INT_BIN=$(BSP_INT_INSTALL)/bin
export BSP_INT_FS=$(BSP_INT_INSTALL)/fs
export BSP_INT_LIB=$(BSP_INT_FS)/lib
export BSP_INT_FS_BIN=$(BSP_INT_FS)/bin
export BSP_INT_FS_USR=$(BSP_INT_FS)/usr/bin
export BSP_INT_FS_USEFS=$(BSP_INT_FS)/userfs/bin
export BSP_INT_FS_USR_SCRIPT=$(BSP_INT_FS)/usr/script
ifneq ($(strip $(TCSUPPORT_OPENWRT)),)
export BSP_EXCL_INSTALL=$(KERNEL_BUILD_DIR)/install_bspapp_exclusive
else
export BSP_EXCL_INSTALL=$(BSP_ROOTDIR)/install_bspapp_exclusive
endif
export BSP_EXCL_FS=$(BSP_EXCL_INSTALL)/fs
export BSP_EXCL_LIB=$(BSP_EXCL_FS)/lib
export BSP_EXCL_INC=$(BSP_EXCL_INSTALL)/inc
export BSP_EXCL_FS_BIN=$(BSP_EXCL_FS)/bin
export BSP_EXCL_FS_USR=$(BSP_EXCL_FS)/usr/bin
export BSP_EXCL_FS_USEFS=$(BSP_EXCL_FS)/userfs
export BSP_EXCL_FS_USEFS_BIN=$(BSP_EXCL_FS)/userfs/bin

export FS_GEN_DIR=$(APP_BSP_DIR)/filesystem_bsp

#mtk
# export BSP_API_MTK_ITF_DIR=$(BSP_API_DIR)/mtk_itf
# export BSP_API_MTK_ITF_QOS_DIR = $(BSP_API_MTK_ITF_DIR)/mtk_itf_qos
# export BSP_API_MTK_ITF_SWITCH_DIR = $(BSP_API_MTK_ITF_DIR)/mtk_itf_switch
# export BSP_API_MTK_ITF_FE_DIR=$(BSP_API_MTK_ITF_DIR)/mtk_itf_fe
# export BSP_API_MTK_ITF_SIMULATION_DIR=$(BSP_API_MTK_ITF_DIR)/mtk_itf_simulation
# export BSP_API_MTK_ITF_PPE_DIR=$(BSP_API_MTK_ITF_DIR)/mtk_itf_ppe

export VOIP_BSP_DIR=$(TRUNK_DIR)/BSP/voip_bsp
export VOIP_BSP_CRITICAL_DIR=$(TRUNK_DIR)/BSP/critical_ip_bsp/voip_bsp
export VOIP_APP_DIR=$(TRUNK_DIR)/apps/voip_app
export VOIP_APP_CRITICAL_DIR=$(TRUNK_DIR)/apps/critical_ip_app/voip_app
export OLT_APP_CRITICAL_DIR=$(TRUNK_DIR)/apps/critical_ip_app/olt_app/olt_omci/src/frame/
export MESH_APP_DIR=$(TRUNK_DIR)/apps/mesh_app_open
export APP_CRITICALIP_DIR=$(APP_DIR)/critical_ip_app
export VOIP_APP_BSP_DIR=$(APP_BSP_PRIVATEDIR)/voip
export IS_VOIP_BSP_DIR_EXIST=$(if $(wildcard $(VOIP_BSP_DIR)/.),Y,N)
export IS_VOIP_BSP_CRITICAL_DIR_EXIST=$(if $(wildcard $(VOIP_BSP_CRITICAL_DIR)/.),Y,N)
export IS_VOIP_APP_DIR_EXIST=$(if $(wildcard $(VOIP_APP_DIR)/.),Y,N)
export IS_VOIP_APP_CRITICAL_DIR_EXIST=$(if $(wildcard $(VOIP_APP_CRITICAL_DIR)/.),Y,N)
export IS_VOIP_APP_BSP_DIR_EXIST=$(if $(wildcard $(VOIP_APP_BSP_DIR)/.),Y,N)

export XPON_BSP_DIR=$(TRUNK_DIR)/BSP/xpon_bsp
export XPON_BSP_UNOPEN_DIR=$(TRUNK_DIR)/BSP/unopen_ip/xpon_bsp
export OLT_BSP_DIR=$(TRUNK_DIR)/BSP/olt_bsp
export OLT_CRITICAL_BSP_DIR=$(TRUNK_DIR)/BSP/critical_ip_bsp/olt_bsp
export XPON_APP_SDK_DIR=$(TRUNK_DIR)/apps/xpon_app
export XPON_APP_BSP_DIR=$(TRUNK_DIR)/BSP/xpon_app
export OLT_APP_SDK_DIR=$(TRUNK_DIR)/apps/olt_app
export OLT_APP_BSP_DIR=$(TRUNK_DIR)/BSP/olt_app
export GPON_IGMP_DIR=$(XPON_BSP_DIR)/modules/gpon_igmp
export XPON_IGMP_DIR=$(XPON_BSP_DIR)/modules/xpon_igmp
export DPOE_BSP_DIR=$(TRUNK_DIR)/BSP/dpoe_bsp
export IS_XPON_BSP_DIR_EXIST=$(if $(wildcard $(XPON_BSP_DIR)/.),Y,N)
export IS_OLT_BSP_DIR_EXIST=$(if $(wildcard $(OLT_BSP_DIR)/.),Y,N)
export IS_XPON_APP_BSP_DIR_EXIST=$(if $(wildcard $(XPON_APP_BSP_DIR)/.),Y,N)
export IS_XPON_APP_SDK_DIR_EXIST=$(if $(wildcard $(XPON_APP_SDK_DIR)/.),Y,N)
export IS_OLT_APP_BSP_DIR_EXIST=$(if $(wildcard $(OLT_APP_BSP_DIR)/.),Y,N)
export IS_OLT_APP_SDK_DIR_EXIST=$(if $(wildcard $(OLT_APP_SDK_DIR)/.),Y,N)

#should delete later
ifneq ($(strip $(TCSUPPORT_BLAPI)),)

export APP_BSP_API_ECNT_IGMP_LIB_DIR=$(APP_BSP_API_DIR)/hw_driver/ecnt_igmp/lib_src
export APP_BSP_API_ECNT_IGMP_CMD_DIR=$(APP_BSP_API_DIR)/hw_driver/ecnt_igmp/cmd

export APP_BSP_MESH_DIR=$(APP_BSP_API_DIR)/hw_driver/mesh

APP_BSP_API_CPUTEMP_LIB_DIR = $(APP_BSP_API_DIR)/hw_driver/cpu/lib_src
export APP_BSP_API_CPUTEMP_LIB_DIR
APP_BSP_API_CPUTEMP_CMD_DIR = $(APP_BSP_API_DIR)/hw_driver/cpu/cmd

ECNT_EVENT_LIB_DIR=$(APP_BSP_API_DIR)/ecnt_event
APP_BSP_API_DBG_LIB_DIR=$(APP_BSP_API_DIR)/ecnt_lib_dbg
APP_BSP_API_ECNT_PRINTF_DIR=$(APP_BSP_API_DIR)/ecnt_lib_printf
APP_BSP_API_UTL_LIB_DIR=$(APP_BSP_API_DIR)/ecnt_lib_utility
APP_BSP_API_PORTBIND_LIB_DIR=$(APP_BSP_API_DIR)/ecnt_lib_portbind
endif

export APP_TCCI_COMMON_SRC_DIR=$(APP_BSP_LIB_DIR)/tcci_common
export APP_COMPILEOPTION_SRC_DIR=$(APP_BSP_LIB_DIR)/compileoption_lib
export APP_BSP_COMPILEOPTION_LIB_DIR=$(APP_BSP_DIR)/private/compileoption_lib

export PROJECT_APP_DIR=$(TRUNK_DIR)/Project
ifneq ($(strip $(CUSTOM)),)
PROFILE_APP_DIR=$(PROJECT_APP_DIR)/profile/$(CUSTOM)/$(PROFILE)
else
PROFILE_APP_DIR=$(PROJECT_APP_DIR)/profile/$(PROFILE)
endif
export PROJECT_APP_DIR
export PROFILE_APP_DIR
export TOOLS_APP_DIR=$(TRUNK_DIR)/tools

PROJECT_MAKE_INC_DIR=$(TRUNK_DIR)/Project/make_inc
export PROJECT_MAKE_INC_DIR
PROJECT_MAKE_INC_APP_DIR=$(PROJECT_APP_DIR)/make_inc
export PROJECT_MAKE_INC_APP_DIR

PROJECT_LIB_APP_DIR=$(PROJECT_APP_DIR)/lib
export PROJECT_LIB_APP_DIR
ifneq ($(strip $(TCSUPPORT_OPENWRT)),)
VERSION_DIR=$(GLOBAL_INC_DIR)/version
else
VERSION_DIR=$(APP_BSP_DIR)/version
endif
export IS_APPS_DIR_EXIST=$(if $(wildcard $(APP_DIR)/.),Y,N)

export RELEASE_BSP_DIR=$(TRUNK_DIR)/release_bsp

export RELEASE_BSP_UNOPEN_DIR=$(TRUNK_DIR)/release_bsp
export RELEASE_APP_UNOPEN_DIR=$(TRUNK_DIR)/release_bsp

export VOIP_RELEASE_BSP_UNOPEN_DIR=$(RELEASE_BSP_UNOPEN_DIR)/VOIP/BSP/voip_bsp
export VOIP_RELEASE_APP_UNOPEN_DIR=$(RELEASE_APP_UNOPEN_DIR)/VOIP/apps/voip_app

export DOC_DIR=$(TRUNK_DIR)/doc
ifneq ($(strip $(TCSUPPORT_OPENWRT)),)
    include $(PLATFORM_SUBDIR)/defines/openwrt_specify.mk
endif
APP_RATEMANAGER_DIR=$(APP_BSP_PRIVATEDIR)/ratemanager

MODULES_CRITICAL_NPU_DIR=$(TRUNK_DIR)/BSP/critical_ip_bsp/npu_bsp
MODULES_CRITICAL_OLT_BSP_DIR=$(TRUNK_DIR)/BSP/critical_ip_bsp/olt_bsp
MODULES_CRITICAL_NPU_EXT_DIR=$(TRUNK_DIR)/../critical_ip/tclinux_phoenix
MODULES_MD32RV_EXT_DIR=$(MODULES_CRITICAL_NPU_EXT_DIR)/BSP/critical_ip_bsp/npu_bsp/md32rv-sdk
