#Overwite AIROHA PATHS to properly migrate to OpenWRT

export OPENWRT_BUILD_RELEASECODE=1
export RELEASE_PROFILE_DEFAULT=$(SUBTARGET)

export AIROHA_FEEDS_DIR=$(TOPDIR)/feeds/airoha64
export TRUNK_DIR=$(AIROHA_FEEDS_DIR)/tclinux_phoenix
export ECNT_BUILD_DIR=$(AIROHA_FEEDS_DIR)/include
export KERNEL_BUILD_DIR
export KERNEL_DIR=$(LINUX_DIR)
ifneq ($(TCSUPPORT_CPU_AN7583),)
export RELEASE_PROFILE=UNION_AN7583_KITE_LOGAN_EMMC_OPTEE_KERNEL_5_4_demo
endif
