# Define compile flags and variables that shared between BSP and APPS

#ABDT- Airoha Broadband Diagnostic Tool
ifneq ($(strip $(TCSUPPORT_WLAN_AUTO_DEBUG_TOOL)),)
TC_CFLAGS+=-DTCSUPPORT_WLAN_AUTO_DEBUG_TOOL
export TCSUPPORT_WLAN_AUTO_DEBUG_TOOL
endif

ifneq ($(strip $(TCSUPPORT_SOE)),)
export TCSUPPORT_SOE=1
COMMON_CFLAGS+=-DTCSUPPORT_SOE
endif

ifneq ($(strip $(TCSUPPORT_UBIFS)),)
export TCSUPPORT_UBIFS=1
endif

ifneq ($(strip $(TCSUPPORT_OPENSSL_V1_1)),)
export TCSUPPORT_OPENSSL_V1_1=1
COMMON_CFLAGS+=-DTCSUPPORT_OPENSSL_V1_1
endif

ifneq ($(strip $(TCSUPPORT_CPU_EN7580)),)
export TCSUPPORT_BB_256KB=1
COMMON_CFLAGS+=-DTCSUPPORT_BB_256KB
endif

ifneq ($(strip $(TCSUPPORT_PON_SFU_HGU_HYBRID)),)
export TCSUPPORT_PON_SFU_HGU_HYBRID=1
COMMON_CFLAGS+=-DTCSUPPORT_PON_SFU_HGU_HYBRID
endif

ifneq ($(strip $(TCSUPPORT_CPU_EN7528)),)
ifneq ($(strip $(TCSUPPORT_LITTLE_ENDIAN)),)
export TCSUPPORT_BB_256KB=1
COMMON_CFLAGS+=-DTCSUPPORT_BB_256KB
endif
endif

ifneq ($(strip $(TCSUPPORT_CPU_EN7521) $(TCSUPPORT_CPU_EN7516)),)
ifneq ($(strip $(TCSUPPORT_SECURE_BOOT)),)
export TCSUPPORT_BB_256KB=1
COMMON_CFLAGS+=-DTCSUPPORT_BB_256KB
endif
endif

export TCSUPPORT_BOOTROM_LARGE_SIZE=1
COMMON_CFLAGS+=-DTCSUPPORT_BOOTROM_LARGE_SIZE

ifneq ($(strip $(TCSUPPORT_DZS)),)
export TCSUPPORT_DZS=1
COMMON_CFLAGS+=-DTCSUPPORT_DZS
endif

ifneq ($(strip $(TCSUPPORT_DM_VERITY)),)
export TCSUPPORT_DM_VERITY=1
COMMON_CFLAGS+=-DTCSUPPORT_DM_VERITY
endif
